//! QIR (Quantum Intermediate Representation) backend — placeholder.
//!
//! This module is currently a **stub**: it does not lower nialang programs to
//! quantum operations. It only emits a recognizable QIR-flavored LLVM module
//! (opaque `%Qubit` / `%Result` types, a handful of `__quantum__qis__*`
//! intrinsic declarations, QIR module flags, and an empty `@Main` entry).
//!
//! The stub exists so that the CLI can already accept `-q` / `--qir`, the
//! pipeline can already dispatch on a `Backend` choice, and tests can pin the
//! shape of the emitted text. Real lowering (mapping `quant { ... }` blocks
//! and quantum intrinsics to `__quantum__qis__*` calls under a chosen QIR
//! profile) is intentionally left for follow-up changes.
//!
//! Inputs come from the same validated AST as the default LLVM backend
//! (`crate::backend::codegen::emit_module`); for now they are ignored.

use std::collections::HashMap;

use crate::ast::{EnumDef, FnDef, StructDef, VectorDef};
use crate::semantics::typecheck::FnSig;

/// Emits a stub QIR-flavored LLVM module. The signature mirrors
/// [`crate::backend::codegen::emit_module`] so the driver can dispatch on a
/// `Backend` enum without per-backend argument shaping.
pub fn emit_module(
    _structs: &[StructDef],
    _enums: &[EnumDef],
    _vectors: &[VectorDef],
    _fns: &[FnDef],
    _fn_sigs: &HashMap<String, FnSig>,
) -> String {
    String::from(STUB_QIR_MODULE)
}

const STUB_QIR_MODULE: &str = "; generated by nialang (QIR backend — stub)\n\
; This is a placeholder; nialang programs are not yet lowered to QIR.\n\
; Real lowering will map `quant { ... }` blocks to __quantum__qis__* calls.\n\
\n\
target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\"\n\
target triple = \"unknown-unknown-unknown\"\n\
\n\
%Qubit = type opaque\n\
%Result = type opaque\n\
\n\
declare void @__quantum__qis__h__body(%Qubit*)\n\
declare void @__quantum__qis__x__body(%Qubit*)\n\
declare void @__quantum__qis__cnot__body(%Qubit*, %Qubit*)\n\
declare void @__quantum__qis__mz__body(%Qubit*, %Result*)\n\
declare void @__quantum__rt__result_record_output(%Result*, i8*)\n\
\n\
define void @Main() #0 {\n\
entry:\n\
  ret void\n\
}\n\
\n\
attributes #0 = { \"entry_point\" \"qir_profiles\"=\"base_profile\" \"required_num_qubits\"=\"0\" \"required_num_results\"=\"0\" }\n\
\n\
!llvm.module.flags = !{!0, !1, !2, !3}\n\
!0 = !{i32 1, !\"qir_major_version\", i32 1}\n\
!1 = !{i32 7, !\"qir_minor_version\", i32 0}\n\
!2 = !{i32 1, !\"dynamic_qubit_management\", i1 false}\n\
!3 = !{i32 1, !\"dynamic_result_management\", i1 false}\n";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stub_contains_qir_marker_and_entry_point() {
        let ir = emit_module(&[], &[], &[], &[], &HashMap::new());
        assert!(ir.contains("QIR backend"), "stub header missing:\n{ir}");
        assert!(ir.contains("define void @Main()"), "stub entry missing:\n{ir}");
        assert!(ir.contains("qir_major_version"), "qir module flag missing:\n{ir}");
        assert!(ir.contains("%Qubit = type opaque"), "qubit type missing:\n{ir}");
    }
}
