use std::collections::HashMap;
use std::fmt::Write as _;

use crate::ast::{EnumDef, EnumVariantFields, Expr, FnDef, MatchPattern, Stmt, StructDef, Ty};
use crate::nia_std::{ALLOC, DEALLOC, PRINTLN, REALLOC};
use crate::semantics::typecheck::FnSig;

/// Emits complete textual LLVM module from already-validated AST.
///
/// ## Preconditions
/// Input program is expected to be successfully typechecked; codegen uses that
/// invariant and contains `unreachable!` branches for impossible typed states.
///
/// ## Emission order
/// 1. Target header.
/// 2. Std prelude (`printf` declaration and text/format globals).
/// 3. Struct LLVM type declarations.
/// 4. Function definitions.
pub fn emit_module(
    structs: &[StructDef],
    enums: &[EnumDef],
    fns: &[FnDef],
    fn_sigs: &HashMap<String, FnSig>,
) -> String {
    let mut out = String::new();
    out.push_str("; generated by nialang\n");
    out.push_str("target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\"\n");
    out.push_str("target triple = \"unknown-unknown-unknown\"\n\n");
    out.push_str(crate::nia_std::llvm_prelude());
    out.push_str(&emit_struct_print_constants(structs));
    out.push_str(&emit_enum_print_constants(enums));

    for s in structs {
        out.push_str(&struct_type_decl(s));
        out.push('\n');
    }
    for e in enums {
        out.push_str(&enum_type_decl(e, structs));
        out.push('\n');
    }
    if !structs.is_empty() || !enums.is_empty() {
        out.push('\n');
    }

    for f in fns {
        out.push_str(&emit_fn(f, structs, enums, fn_sigs));
        out.push('\n');
    }
    out
}

/// Escapes arbitrary bytes into LLVM `c"..."` literal form.
///
/// Printable ASCII is emitted directly, while control/non-ASCII bytes are emitted as `\XX`.
fn llvm_c_escape(bytes: &[u8]) -> String {
    let mut s = String::new();
    for &b in bytes {
        match b {
            b'\\' => s.push_str("\\5C"),
            b'"' => s.push_str("\\22"),
            0x20..=0x7e => s.push(char::from(b)),
            _ => {
                let _ = write!(s, "\\{:02X}", b);
            }
        }
    }
    s
}

/// Produces unique global symbol name for named-struct JSON key fragment.
fn struct_field_key_symbol(sname: &str, fname: &str) -> String {
    format!(
        "nialang.std.txt.json.key.{}.{}",
        sanitize(sname),
        sanitize(fname)
    )
}

fn enum_variant_prefix_symbol(ename: &str, vname: &str) -> String {
    format!(
        "nialang.std.txt.enumprefix.{}.{}",
        sanitize(ename),
        sanitize(vname)
    )
}

fn enum_struct_field_key_symbol(ename: &str, vname: &str, fname: &str) -> String {
    format!(
        "nialang.std.txt.enumjson.{}.{}.{}",
        sanitize(ename),
        sanitize(vname),
        sanitize(fname)
    )
}

/// Global `Variant: ` strings and JSON keys for enum struct-variant fields (for `println`).
fn emit_enum_print_constants(enums: &[EnumDef]) -> String {
    let mut out = String::new();
    for e in enums {
        for v in &e.variants {
            let prefix = format!("{}: ", v.name);
            let bytes = prefix.as_bytes();
            let sz = bytes.len() + 1;
            let lit = llvm_c_escape(bytes);
            let sym = enum_variant_prefix_symbol(&e.name, &v.name);
            writeln!(
                out,
                "@{} = private unnamed_addr constant [{} x i8] c\"{}\\00\", align 1",
                sym, sz, lit
            )
            .unwrap();
            if let EnumVariantFields::Struct(fs) = &v.fields {
                for (fname, _) in fs {
                    let key = format!("\"{}\": ", fname);
                    let bytes = key.as_bytes();
                    let sz = bytes.len() + 1;
                    let lit = llvm_c_escape(bytes);
                    let sym = enum_struct_field_key_symbol(&e.name, &v.name, fname);
                    writeln!(
                        out,
                        "@{} = private unnamed_addr constant [{} x i8] c\"{}\\00\", align 1",
                        sym, sz, lit
                    )
                    .unwrap();
                }
            }
        }
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

/// Emits global string constants for named-struct JSON key rendering.
fn emit_struct_print_constants(structs: &[StructDef]) -> String {
    let mut out = String::new();
    for s in structs.iter().filter(|s| !s.is_tuple) {
        for (fname, _) in &s.fields {
            let key = format!("\"{}\": ", fname);
            let bytes = key.as_bytes();
            let sz = bytes.len() + 1;
            let lit = llvm_c_escape(bytes);
            let sym = struct_field_key_symbol(&s.name, fname);
            writeln!(
                out,
                "@{} = private unnamed_addr constant [{} x i8] c\"{}\\00\", align 1",
                sym, sz, lit
            )
            .unwrap();
        }
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

/// Maps high-level nialang type into LLVM IR textual type.
fn llvm_ty(t: &Ty, _structs: &[StructDef]) -> String {
    match t {
        Ty::I8 => "i8".into(),
        Ty::U8 => "i8".into(),
        Ty::I16 => "i16".into(),
        Ty::U16 => "i16".into(),
        Ty::I32 => "i32".into(),
        Ty::I64 => "i64".into(),
        Ty::U64 => "i64".into(),
        Ty::I128 => "i128".into(),
        Ty::Isize => "i64".into(),
        Ty::Usize => "i64".into(),
        Ty::U128 => "i128".into(),
        Ty::Bool => "i1".into(),
        Ty::Array(elem, n) => format!("[{} x {}]", n, llvm_ty(elem, _structs)),
        Ty::Struct(n) => format!("%struct.{}", sanitize(n)),
        Ty::Enum(n) => format!("%enum.{}", sanitize(n)),
        Ty::Ptr(_) => "ptr".into(),
        Ty::Unit => "void".into(),
    }
}

/// Signed integer types use `icmp slt` for `..` range checks; unsigned use `icmp ult`.
fn int_ty_signed(t: &Ty) -> bool {
    matches!(
        t,
        Ty::I8 | Ty::I16 | Ty::I32 | Ty::I64 | Ty::I128 | Ty::Isize
    )
}

/// Emits LLVM `%struct.Name = type { ... }` declaration.
fn struct_type_decl(s: &StructDef) -> String {
    let parts: Vec<String> = s.fields.iter().map(|(_, t)| llvm_ty(t, &[])).collect();
    format!(
        "%struct.{} = type {{ {} }}",
        sanitize(&s.name),
        parts.join(", ")
    )
}

fn enum_variant_payload_ty(v: &crate::ast::EnumVariantDef, structs: &[StructDef]) -> String {
    match &v.fields {
        EnumVariantFields::Unit => "i8".into(),
        EnumVariantFields::Tuple(ts) => {
            if ts.len() == 1 {
                llvm_ty(&ts[0], structs)
            } else {
                let inner = ts
                    .iter()
                    .map(|t| llvm_ty(t, structs))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{{ {inner} }}")
            }
        }
        EnumVariantFields::Struct(fs) => {
            let inner = fs
                .iter()
                .map(|(_, t)| llvm_ty(t, structs))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {inner} }}")
        }
    }
}

fn enum_type_decl(e: &EnumDef, structs: &[StructDef]) -> String {
    let mut parts = vec!["i32".to_string()];
    for v in &e.variants {
        parts.push(enum_variant_payload_ty(v, structs));
    }
    format!("%enum.{} = type {{ {} }}", sanitize(&e.name), parts.join(", "))
}

/// Sanitizes user-defined names for safe LLVM symbol usage.
fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// `arr[i][j]…` as a chain ending in a local name (for GEP-based load/store).
fn collect_array_index_chain(mut e: &Expr) -> Option<(String, Vec<&Expr>)> {
    let mut idxs = Vec::new();
    loop {
        match e {
            Expr::Index(a, i) => {
                idxs.push(i.as_ref());
                e = a.as_ref();
            }
            Expr::Ident(n) => {
                idxs.reverse();
                return Some((n.clone(), idxs));
            }
            _ => return None,
        }
    }
}

struct Gen<'a> {
    structs: &'a [StructDef],
    enums: &'a [EnumDef],
    fn_sigs: &'a HashMap<String, FnSig>,
    tmp: u32,
    lbl: u32,
    out: String,
    terminated: bool,
    /// Labels of `loop.exit` for nested `loop`; `break` branches to the top.
    loop_exit_stack: Vec<String>,
}

impl<'a> Gen<'a> {
    /// Constructs function-level codegen state.
    fn new(structs: &'a [StructDef], enums: &'a [EnumDef], fn_sigs: &'a HashMap<String, FnSig>) -> Self {
        Self {
            structs,
            enums,
            fn_sigs,
            tmp: 0,
            lbl: 0,
            out: String::new(),
            terminated: false,
            loop_exit_stack: Vec::new(),
        }
    }

    /// Allocates fresh SSA temporary id.
    fn fresh(&mut self) -> String {
        let n = self.tmp;
        self.tmp += 1;
        format!("t{n}")
    }

    /// Allocates fresh basic-block label id.
    fn fresh_label(&mut self, prefix: &str) -> String {
        let n = self.lbl;
        self.lbl += 1;
        format!("{prefix}.{n}")
    }

    /// Emits pointer to first byte of global string constant.
    fn fmt_ptr(&mut self, sym: &str, size: u32) -> String {
        let tmp = self.fresh();
        writeln!(
            self.out,
            "  %{} = getelementptr inbounds [{} x i8], ptr @{}, i64 0, i64 0",
            tmp, size, sym
        )
        .unwrap();
        format!("%{tmp}")
    }

    /// Emits plain `printf` call for constant text fragment.
    fn emit_printf_text(&mut self, sym: &str, size: u32) {
        let p = self.fmt_ptr(sym, size);
        writeln!(self.out, "  call i32 (ptr, ...) @printf(ptr {})", p).unwrap();
    }

    /// Convenience wrapper for dynamic known-at-runtime `usize` sizes.
    fn emit_printf_text_dynamic(&mut self, sym: &str, size: usize) {
        self.emit_printf_text(sym, size as u32);
    }

    /// Looks up struct definition by source-level name.
    fn struct_def(&self, name: &str) -> Option<&StructDef> {
        self.structs.iter().find(|s| s.name == name)
    }

    fn enum_tag(&self, enum_name: &str, variant: &str) -> Option<i32> {
        let e = self.enums.iter().find(|e| e.name == enum_name)?;
        e.variants
            .iter()
            .position(|v| v.name == variant)
            .map(|i| i as i32)
    }

    fn enum_variant_index(&self, enum_name: &str, variant: &str) -> Option<usize> {
        let e = self.enums.iter().find(|e| e.name == enum_name)?;
        e.variants.iter().position(|v| v.name == variant)
    }

    fn enum_variant_def(&self, enum_name: &str, variant: &str) -> Option<&crate::ast::EnumVariantDef> {
        let e = self.enums.iter().find(|e| e.name == enum_name)?;
        e.variants.iter().find(|v| v.name == variant)
    }

    fn emit_sizeof_i64(&mut self, ty: &Ty) -> String {
        let ty_ll = llvm_ty(ty, self.structs);
        let gep = self.fresh();
        let sz = self.fresh();
        writeln!(
            self.out,
            "  %{} = getelementptr {}, ptr null, i64 1",
            gep, ty_ll
        )
        .unwrap();
        writeln!(self.out, "  %{} = ptrtoint ptr %{} to i64", sz, gep).unwrap();
        format!("%{sz}")
    }

    /// Emits primitive scalar printing (`int`, `bool`, pointer) with optional newline.
    ///
    /// This function centralizes ABI-sensitive formatting:
    /// - sign/zero extension for small integers,
    /// - `%lld`/`%llu` for 64-bit lanes,
    /// - split hi/lo printing for 128-bit values,
    /// - `ptrtoint` for pointer hex output.
    fn emit_print_primitive(&mut self, ty: &Ty, v: &str, newline: bool) {
        match ty {
            Ty::I8 => {
                let t = self.fresh();
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.i32", 4)
                } else {
                    ("nialang.std.fmt.i32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(self.out, "  %{} = sext i8 {} to i32", t, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 %{})",
                    p, t
                )
                .unwrap();
            }
            Ty::U8 => {
                let t = self.fresh();
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.u32", 4)
                } else {
                    ("nialang.std.fmt.u32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(self.out, "  %{} = zext i8 {} to i32", t, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 %{})",
                    p, t
                )
                .unwrap();
            }
            Ty::I16 => {
                let t = self.fresh();
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.i32", 4)
                } else {
                    ("nialang.std.fmt.i32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(self.out, "  %{} = sext i16 {} to i32", t, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 %{})",
                    p, t
                )
                .unwrap();
            }
            Ty::U16 => {
                let t = self.fresh();
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.u32", 4)
                } else {
                    ("nialang.std.fmt.u32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(self.out, "  %{} = zext i16 {} to i32", t, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 %{})",
                    p, t
                )
                .unwrap();
            }
            Ty::I32 => {
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.i32", 4)
                } else {
                    ("nialang.std.fmt.i32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 {})",
                    p, v
                )
                .unwrap();
            }
            Ty::I64 | Ty::Isize => {
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.i64", 6)
                } else {
                    ("nialang.std.fmt.i64.nn", 5)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i64 {})",
                    p, v
                )
                .unwrap();
            }
            Ty::U64 | Ty::Usize => {
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.u64", 6)
                } else {
                    ("nialang.std.fmt.u64.nn", 5)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i64 {})",
                    p, v
                )
                .unwrap();
            }
            Ty::Bool => {
                let t = self.fresh();
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.u32", 4)
                } else {
                    ("nialang.std.fmt.u32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(self.out, "  %{} = zext i1 {} to i32", t, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 %{})",
                    p, t
                )
                .unwrap();
            }
            Ty::I128 | Ty::U128 => {
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.i128hex", 18)
                } else {
                    ("nialang.std.fmt.i128hex.nn", 17)
                };
                let p = self.fmt_ptr(sym, sz);
                let hi128 = self.fresh();
                let hi64 = self.fresh();
                let lo64 = self.fresh();
                writeln!(self.out, "  %{} = lshr i128 {}, 64", hi128, v).unwrap();
                writeln!(self.out, "  %{} = trunc i128 %{} to i64", hi64, hi128).unwrap();
                writeln!(self.out, "  %{} = trunc i128 {} to i64", lo64, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i64 %{}, i64 %{})",
                    p, hi64, lo64
                )
                .unwrap();
            }
            Ty::Ptr(_) => {
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.ptrhex", 8)
                } else {
                    ("nialang.std.fmt.ptrhex.nn", 7)
                };
                let p = self.fmt_ptr(sym, sz);
                let addr = self.fresh();
                writeln!(self.out, "  %{} = ptrtoint ptr {} to i64", addr, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i64 %{})",
                    p, addr
                )
                .unwrap();
            }
            Ty::Array(_, _) | Ty::Struct(_) | Ty::Enum(_) | Ty::Unit => unreachable!("typechecked"),
        }
    }

    /// Emits array printing in `[a, b, c]` style with optional trailing newline.
    ///
    /// Elements are extracted using `extractvalue` and recursively rendered
    /// via `emit_print_value`, so nested printable composites are supported.
    fn emit_print_array(&mut self, elem_ty: &Ty, n: usize, arr_v: &str, newline: bool) {
        self.emit_printf_text("nialang.std.txt.arr_open", 2);
        for i in 0..n {
            if i > 0 {
                self.emit_printf_text("nialang.std.txt.arr_sep", 3);
            }
            let ev = self.fresh();
            let llvm_arr = format!("[{} x {}]", n, llvm_ty(elem_ty, self.structs));
            writeln!(
                self.out,
                "  %{} = extractvalue {} {}, {}",
                ev, llvm_arr, arr_v, i
            )
            .unwrap();
            self.emit_print_value(elem_ty, &format!("%{ev}"), false);
        }
        if newline {
            self.emit_printf_text("nialang.std.txt.arr_close_ln", 3);
        } else {
            self.emit_printf_text("nialang.std.txt.arr_close", 2);
        }
    }

    /// Emits struct printing in two source-level forms:
    /// - named structs -> JSON-like object form (`{"x": 1, "y": 2}`)
    /// - tuple structs -> tuple form (`(1, 2)`)
    ///
    /// Field values are pulled from aggregate SSA value via `extractvalue` and then
    /// recursively rendered according to each field type.
    fn emit_print_struct(&mut self, sname: &str, struct_v: &str, newline: bool) {
        let sdef = self.struct_def(sname).expect("typechecked struct");
        let is_tuple = sdef.is_tuple;
        let fields = sdef.fields.clone();
        if is_tuple {
            self.emit_printf_text("nialang.std.txt.tuple_open", 2);
            for (i, (_, fty)) in fields.iter().enumerate() {
                if i > 0 {
                    self.emit_printf_text("nialang.std.txt.arr_sep", 3);
                }
                let fv = self.fresh();
                let llvm_st = format!("%struct.{}", sanitize(sname));
                writeln!(
                    self.out,
                    "  %{} = extractvalue {} {}, {}",
                    fv, llvm_st, struct_v, i
                )
                .unwrap();
                self.emit_print_value(fty, &format!("%{fv}"), false);
            }
            if newline {
                self.emit_printf_text("nialang.std.txt.tuple_close_ln", 3);
            } else {
                self.emit_printf_text("nialang.std.txt.tuple_close", 2);
            }
            return;
        }

        self.emit_printf_text("nialang.std.txt.obj_open", 2);
        for (i, (fname, fty)) in fields.iter().enumerate() {
            if i > 0 {
                self.emit_printf_text("nialang.std.txt.arr_sep", 3);
            }
            let key_sym = struct_field_key_symbol(sname, fname);
            let key_sz = fname.as_bytes().len() + 5;
            self.emit_printf_text_dynamic(&key_sym, key_sz);
            let fv = self.fresh();
            let llvm_st = format!("%struct.{}", sanitize(sname));
            writeln!(
                self.out,
                "  %{} = extractvalue {} {}, {}",
                fv, llvm_st, struct_v, i
            )
            .unwrap();
            self.emit_print_value(fty, &format!("%{fv}"), false);
        }
        if newline {
            self.emit_printf_text("nialang.std.txt.obj_close_ln", 3);
        } else {
            self.emit_printf_text("nialang.std.txt.obj_close", 2);
        }
    }

    /// Prints enum as `Variant: <payload>` (unit: `Variant: ()` with newline when requested).
    fn emit_print_enum(&mut self, ename: &str, ev: &str, newline: bool) {
        let edef = self.enums.iter().find(|e| e.name == ename).expect("typechecked");
        let enum_ll = format!("%enum.{}", sanitize(ename));
        let tag = self.fresh();
        writeln!(
            self.out,
            "  %{} = extractvalue {} {}, 0",
            tag, enum_ll, ev
        )
        .unwrap();
        let default_lbl = self.fresh_label("println.enum.default");
        let cont_lbl = self.fresh_label("println.enum.cont");
        let arm_lbls: Vec<String> = edef
            .variants
            .iter()
            .map(|_| self.fresh_label("println.enum.arm"))
            .collect();
        writeln!(self.out, "  switch i32 %{}, label %{} [", tag, default_lbl).unwrap();
        for (i, _) in edef.variants.iter().enumerate() {
            writeln!(self.out, "    i32 {}, label %{}", i as i32, arm_lbls[i]).unwrap();
        }
        writeln!(self.out, "  ]").unwrap();
        writeln!(self.out, "{}:", default_lbl).unwrap();
        writeln!(self.out, "  unreachable").unwrap();

        for (i, vdef) in edef.variants.iter().enumerate() {
            writeln!(self.out, "{}:", arm_lbls[i]).unwrap();
            let sym = enum_variant_prefix_symbol(ename, &vdef.name);
            let prefix = format!("{}: ", vdef.name);
            let prefix_len = prefix.as_bytes().len() + 1;
            self.emit_printf_text_dynamic(&sym, prefix_len);
            let payload_idx = i + 1;
            match &vdef.fields {
                EnumVariantFields::Unit => {
                    self.emit_printf_text("nialang.std.txt.tuple_open", 2);
                    if newline {
                        self.emit_printf_text("nialang.std.txt.tuple_close_ln", 3);
                    } else {
                        self.emit_printf_text("nialang.std.txt.tuple_close", 2);
                    }
                }
                EnumVariantFields::Tuple(ts) if ts.len() == 1 => {
                    let pl = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = extractvalue {} {}, {}",
                        pl, enum_ll, ev, payload_idx
                    )
                    .unwrap();
                    self.emit_print_value(&ts[0], &format!("%{pl}"), newline);
                }
                EnumVariantFields::Tuple(ts) => {
                    let pl = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = extractvalue {} {}, {}",
                        pl, enum_ll, ev, payload_idx
                    )
                    .unwrap();
                    let payload_ll = {
                        let inner = ts
                            .iter()
                            .map(|t| llvm_ty(t, self.structs))
                            .collect::<Vec<_>>()
                            .join(", ");
                        format!("{{ {inner} }}")
                    };
                    self.emit_printf_text("nialang.std.txt.tuple_open", 2);
                    for j in 0..ts.len() {
                        if j > 0 {
                            self.emit_printf_text("nialang.std.txt.arr_sep", 3);
                        }
                        let fv = self.fresh();
                        writeln!(
                            self.out,
                            "  %{} = extractvalue {} %{}, {}",
                            fv, payload_ll, pl, j
                        )
                        .unwrap();
                        self.emit_print_value(&ts[j], &format!("%{fv}"), false);
                    }
                    if newline {
                        self.emit_printf_text("nialang.std.txt.tuple_close_ln", 3);
                    } else {
                        self.emit_printf_text("nialang.std.txt.tuple_close", 2);
                    }
                }
                EnumVariantFields::Struct(fs) => {
                    let pl = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = extractvalue {} {}, {}",
                        pl, enum_ll, ev, payload_idx
                    )
                    .unwrap();
                    let payload_ll = {
                        let inner = fs
                            .iter()
                            .map(|(_, t)| llvm_ty(t, self.structs))
                            .collect::<Vec<_>>()
                            .join(", ");
                        format!("{{ {inner} }}")
                    };
                    self.emit_printf_text("nialang.std.txt.obj_open", 2);
                    for (j, (fname, fty)) in fs.iter().enumerate() {
                        if j > 0 {
                            self.emit_printf_text("nialang.std.txt.arr_sep", 3);
                        }
                        let ksym = enum_struct_field_key_symbol(ename, &vdef.name, fname);
                        let key = format!("\"{}\": ", fname);
                        let key_sz = key.as_bytes().len() + 1;
                        self.emit_printf_text_dynamic(&ksym, key_sz);
                        let fv = self.fresh();
                        writeln!(
                            self.out,
                            "  %{} = extractvalue {} %{}, {}",
                            fv, payload_ll, pl, j
                        )
                        .unwrap();
                        self.emit_print_value(fty, &format!("%{fv}"), false);
                    }
                    if newline {
                        self.emit_printf_text("nialang.std.txt.obj_close_ln", 3);
                    } else {
                        self.emit_printf_text("nialang.std.txt.obj_close", 2);
                    }
                }
            }
            writeln!(self.out, "  br label %{}", cont_lbl).unwrap();
        }
        writeln!(self.out, "{}:", cont_lbl).unwrap();
    }

    /// Recursive dispatcher for printable value lowering.
    ///
    /// Keeps all `println` formatting behavior in one place and ensures nested
    /// composites (array/struct of array/struct/primitive/pointer) print consistently.
    fn emit_print_value(&mut self, ty: &Ty, v: &str, newline: bool) {
        match ty {
            Ty::Array(elem, n) => {
                self.emit_print_array(elem, *n, v, newline);
            }
            Ty::Struct(sname) => {
                self.emit_print_struct(sname, v, newline);
            }
            Ty::Enum(ename) => {
                self.emit_print_enum(ename, v, newline);
            }
            _ => self.emit_print_primitive(ty, v, newline),
        }
    }

    /// Resolves numeric field index for named/tuple field access codegen.
    fn struct_idx(&self, sname: &str, field: &str) -> Option<u32> {
        let s = self.structs.iter().find(|s| s.name == sname)?;
        s.fields
            .iter()
            .position(|(n, _)| n == field)
            .map(|i| i as u32)
    }

    /// Emits one full LLVM function definition.
    ///
    /// ## Strategy
    /// - materialize params into stack slots for uniform local-variable handling,
    /// - lower statements in order, supporting early termination on `return`,
    /// - emit implicit final return from block tail for non-void functions.
    ///
    /// The function body is emitted in SSA-with-stack-slots style (simple and explicit).
    fn emit_fn(mut self, f: &FnDef) -> String {
        self.out.clear();
        let sig = self.fn_sigs.get(&f.name).expect("typechecked sig");
        let ret_ll = match &sig.ret {
            None => "void".into(),
            Some(t) => llvm_ty(t, self.structs),
        };
        let mut params = Vec::new();
        for ((pname, _), pty) in f.params.iter().zip(&sig.params) {
            let ll = llvm_ty(pty, self.structs);
            let ps = sanitize(pname);
            params.push(format!("{ll} %{ps}"));
        }
        writeln!(
            self.out,
            "define {} @{}({}) {{",
            ret_ll,
            sanitize(&f.name),
            params.join(", ")
        )
        .unwrap();
        writeln!(self.out, "entry:").unwrap();

        // Allocate and initialize stack slots for all parameters to unify load/store path
        // with local variables.
        let mut local_ptr: HashMap<String, (Ty, String)> = HashMap::new();
        for ((pname, _), pty) in f.params.iter().zip(&sig.params) {
            let ps = sanitize(pname);
            let ptr = format!("%{ps}.addr");
            writeln!(
                self.out,
                "  {} = alloca {}",
                ptr,
                llvm_ty(pty, self.structs)
            )
            .unwrap();
            writeln!(
                self.out,
                "  store {} %{ps}, ptr {}",
                llvm_ty(pty, self.structs),
                ptr
            )
            .unwrap();
            local_ptr.insert(pname.clone(), (pty.clone(), ptr));
        }

        for st in &f.body.stmts {
            self.emit_stmt(st, &mut local_ptr, sig.ret.as_ref());
            if self.terminated {
                break;
            }
        }

        if self.terminated {
            writeln!(self.out, "}}").unwrap();
            return self.out;
        }

        if let Some(ret_ty) = &sig.ret {
            let tail = f.body.tail.as_ref().unwrap();
            let (t, v) = self.emit_expr(tail, &local_ptr, Some(ret_ty));
            debug_assert!(types_match(&t, ret_ty));
            writeln!(self.out, "  ret {} {}", llvm_ty(ret_ty, self.structs), v).unwrap();
        } else {
            writeln!(self.out, "  ret void").unwrap();
        }

        writeln!(self.out, "}}").unwrap();
        self.out
    }

    /// Emits one statement into current function body.
    ///
    /// `locals` maps source names to `(type, stack_ptr)` and is cloned for `if` branch
    /// lowering to keep branch-local mutations isolated.
    fn emit_stmt(
        &mut self,
        st: &Stmt,
        locals: &mut HashMap<String, (Ty, String)>,
        fn_ret: Option<&Ty>,
    ) {
        match st {
            Stmt::Let { name, ty, init } => {
                let (t, v) = self.emit_expr(init, locals, ty.as_ref());
                let ptr = format!("%{}.addr", sanitize(name));
                writeln!(self.out, "  {} = alloca {}", ptr, llvm_ty(&t, self.structs)).unwrap();
                writeln!(
                    self.out,
                    "  store {} {}, ptr {}",
                    llvm_ty(&t, self.structs),
                    v,
                    ptr
                )
                .unwrap();
                locals.insert(name.clone(), (t, ptr));
            }
            Stmt::Expr(e) => {
                self.emit_expr(e, locals, None);
            }
            Stmt::Assign { target, value } => {
                let (tt, ptr_v) = self.emit_assign_ptr(target, locals);
                let (vt, vv) = self.emit_expr(value, locals, Some(&tt));
                debug_assert!(types_match(&tt, &vt));
                writeln!(
                    self.out,
                    "  store {} {}, ptr {}",
                    llvm_ty(&tt, self.structs),
                    vv,
                    ptr_v
                )
                .unwrap();
            }
            Stmt::Return(e) => {
                let Some(ret_ty) = fn_ret else {
                    unreachable!("typechecked")
                };
                let (t, v) = self.emit_expr(e, locals, Some(ret_ty));
                debug_assert!(types_match(&t, ret_ty));
                writeln!(self.out, "  ret {} {}", llvm_ty(ret_ty, self.structs), v).unwrap();
                self.terminated = true;
            }
            Stmt::Break => {
                let Some(exit) = self.loop_exit_stack.last() else {
                    panic!("internal: `break` should be rejected by typecheck outside `loop`");
                };
                writeln!(self.out, "  br label %{}", exit).unwrap();
                self.terminated = true;
            }
            Stmt::If { cond, then_block } => {
                let (ct, cv) = self.emit_expr(cond, locals, Some(&Ty::Bool));
                debug_assert!(matches!(ct, Ty::Bool));
                let then_lbl = self.fresh_label("if.then");
                let cont_lbl = self.fresh_label("if.cont");
                writeln!(
                    self.out,
                    "  br i1 {}, label %{}, label %{}",
                    cv, then_lbl, cont_lbl
                )
                .unwrap();
                writeln!(self.out, "{}:", then_lbl).unwrap();
                let mut then_locals = locals.clone();
                self.terminated = false;
                for st in &then_block.stmts {
                    self.emit_stmt(st, &mut then_locals, fn_ret);
                    if self.terminated {
                        break;
                    }
                }
                if !self.terminated {
                    if let Some(tail) = &then_block.tail {
                        self.emit_expr(tail, &then_locals, None);
                    }
                    writeln!(self.out, "  br label %{}", cont_lbl).unwrap();
                }
                self.terminated = false;
                writeln!(self.out, "{}:", cont_lbl).unwrap();
            }
            Stmt::While { cond, body } => {
                if self.terminated {
                    return;
                }
                let cond_lbl = self.fresh_label("while.cond");
                let body_lbl = self.fresh_label("while.body");
                let exit_lbl = self.fresh_label("while.exit");
                writeln!(self.out, "  br label %{}", cond_lbl).unwrap();

                writeln!(self.out, "{}:", cond_lbl).unwrap();
                let (ct, cv) = self.emit_expr(cond, locals, Some(&Ty::Bool));
                debug_assert!(matches!(ct, Ty::Bool));
                writeln!(
                    self.out,
                    "  br i1 {}, label %{}, label %{}",
                    cv, body_lbl, exit_lbl
                )
                .unwrap();

                writeln!(self.out, "{}:", body_lbl).unwrap();
                let mut body_locals = locals.clone();
                self.terminated = false;
                for st in &body.stmts {
                    self.emit_stmt(st, &mut body_locals, fn_ret);
                    if self.terminated {
                        break;
                    }
                }
                if !self.terminated {
                    if let Some(tail) = &body.tail {
                        self.emit_expr(tail, &body_locals, None);
                    }
                    writeln!(self.out, "  br label %{}", cond_lbl).unwrap();
                }
                self.terminated = false;
                writeln!(self.out, "{}:", exit_lbl).unwrap();
            }
            Stmt::Loop { body } => {
                if self.terminated {
                    return;
                }
                let iter_lbl = self.fresh_label("loop.iter");
                let exit_lbl = self.fresh_label("loop.exit");
                self.loop_exit_stack.push(exit_lbl.clone());

                writeln!(self.out, "  br label %{}", iter_lbl).unwrap();
                writeln!(self.out, "{}:", iter_lbl).unwrap();
                let mut body_locals = locals.clone();
                self.terminated = false;
                for st in &body.stmts {
                    self.emit_stmt(st, &mut body_locals, fn_ret);
                    if self.terminated {
                        break;
                    }
                }
                if !self.terminated {
                    if let Some(tail) = &body.tail {
                        self.emit_expr(tail, &body_locals, None);
                    }
                    writeln!(self.out, "  br label %{}", iter_lbl).unwrap();
                }
                self.loop_exit_stack.pop();
                self.terminated = false;
                writeln!(self.out, "{}:", exit_lbl).unwrap();
            }
            Stmt::For {
                var,
                start,
                end,
                body,
            } => {
                if self.terminated {
                    return;
                }
                let pre = self.fresh_label("for.pre");
                let header = self.fresh_label("for.header");
                let body_lbl = self.fresh_label("for.body");
                let latch = self.fresh_label("for.latch");
                let exit = self.fresh_label("for.exit");

                writeln!(self.out, "  br label %{}", pre).unwrap();
                writeln!(self.out, "{}:", pre).unwrap();
                let (t_ev, v_start) = self.emit_expr(start, locals, None);
                let (_, v_end) = self.emit_expr(end, locals, Some(&t_ev));
                let ll = llvm_ty(&t_ev, self.structs);
                let slot = self.fresh();
                let var_ptr = format!("%{}.{}", sanitize(var), slot);
                writeln!(self.out, "  {} = alloca {}", var_ptr, ll).unwrap();
                writeln!(self.out, "  br label %{}", header).unwrap();

                writeln!(self.out, "{}:", header).unwrap();
                let iv = self.fresh();
                let iv_next = self.fresh();
                let cmp = self.fresh();
                let icmp_op = if int_ty_signed(&t_ev) {
                    "slt"
                } else {
                    "ult"
                };
                writeln!(
                    self.out,
                    "  %{} = phi {} [ {}, %{} ], [ %{}, %{} ]",
                    iv, ll, v_start, pre, iv_next, latch
                )
                .unwrap();
                writeln!(
                    self.out,
                    "  %{} = icmp {} {} %{}, {}",
                    cmp, icmp_op, ll, iv, v_end
                )
                .unwrap();
                writeln!(
                    self.out,
                    "  br i1 %{}, label %{}, label %{}",
                    cmp, body_lbl, exit
                )
                .unwrap();

                writeln!(self.out, "{}:", body_lbl).unwrap();
                writeln!(
                    self.out,
                    "  store {} %{}, ptr {}",
                    ll, iv, var_ptr
                )
                .unwrap();
                let mut body_locals = locals.clone();
                body_locals.insert(var.clone(), (t_ev.clone(), var_ptr));
                self.terminated = false;
                for st in &body.stmts {
                    self.emit_stmt(st, &mut body_locals, fn_ret);
                    if self.terminated {
                        break;
                    }
                }
                if !self.terminated {
                    if let Some(tail) = &body.tail {
                        self.emit_expr(tail, &body_locals, None);
                    }
                    writeln!(self.out, "  br label %{}", latch).unwrap();
                }
                let body_term = self.terminated;
                self.terminated = false;
                if body_term {
                    panic!("internal: `return` inside `for` should be rejected by typecheck");
                }

                writeln!(self.out, "{}:", latch).unwrap();
                match &t_ev {
                        Ty::I8 | Ty::U8 => {
                            writeln!(self.out, "  %{} = add i8 %{}, 1", iv_next, iv).unwrap();
                        }
                        Ty::I16 | Ty::U16 => {
                            writeln!(self.out, "  %{} = add i16 %{}, 1", iv_next, iv).unwrap();
                        }
                        Ty::I32 => {
                            writeln!(
                                self.out,
                                "  %{} = add nsw i32 %{}, 1",
                                iv_next, iv
                            )
                            .unwrap();
                        }
                        Ty::I64 | Ty::U64 | Ty::Isize | Ty::Usize => {
                            writeln!(self.out, "  %{} = add i64 %{}, 1", iv_next, iv).unwrap();
                        }
                        Ty::I128 => {
                            writeln!(self.out, "  %{} = add i128 %{}, 1", iv_next, iv).unwrap();
                        }
                        Ty::U128 => {
                            writeln!(self.out, "  %{} = add i128 %{}, 1", iv_next, iv).unwrap();
                        }
                        Ty::Array(_, _)
                        | Ty::Struct(_)
                        | Ty::Enum(_)
                        | Ty::Unit
                        | Ty::Ptr(_)
                        | Ty::Bool => unreachable!("typechecked for range"),
                }
                writeln!(self.out, "  br label %{}", header).unwrap();

                writeln!(self.out, "{}:", exit).unwrap();
            }
        }
    }

    /// Emits expression and returns `(type, value)` where value is either:
    /// - immediate literal text, or
    /// - SSA reference like `%t7`.
    ///
    /// Caller decides whether returned value should be stored, returned, printed, etc.
    fn emit_expr(
        &mut self,
        e: &Expr,
        locals: &HashMap<String, (Ty, String)>,
        hint: Option<&Ty>,
    ) -> (Ty, String) {
        match e {
            Expr::Int(n) => match hint {
                Some(Ty::I8) => (Ty::I8, format!("{n}")),
                Some(Ty::U8) => (Ty::U8, format!("{n}")),
                Some(Ty::I16) => (Ty::I16, format!("{n}")),
                Some(Ty::U16) => (Ty::U16, format!("{n}")),
                Some(Ty::I32) | None => (Ty::I32, format!("{n}")),
                Some(Ty::I64) => (Ty::I64, format!("{n}")),
                Some(Ty::U64) => (Ty::U64, format!("{n}")),
                Some(Ty::I128) => (Ty::I128, format!("{n}")),
                Some(Ty::Isize) => (Ty::Isize, format!("{n}")),
                Some(Ty::Usize) => (Ty::Usize, format!("{n}")),
                Some(Ty::U128) => (Ty::U128, format!("{n}")),
                Some(Ty::Struct(_))
                | Some(Ty::Enum(_))
                | Some(Ty::Unit)
                | Some(Ty::Ptr(_))
                | Some(Ty::Bool)
                | Some(Ty::Array(_, _)) => {
                    unreachable!("typechecked")
                }
            },
            Expr::Bool(b) => (Ty::Bool, if *b { "1".into() } else { "0".into() }),
            Expr::Ident(name) => {
                let (ty, ptr) = locals.get(name).expect("checked var");
                let tmp = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = load {}, ptr {}",
                    tmp,
                    llvm_ty(ty, self.structs),
                    ptr
                )
                .unwrap();
                (ty.clone(), format!("%{tmp}"))
            }
            Expr::Neg(inner) => {
                let (t, v) = self.emit_expr(inner, locals, None);
                let tmp = self.fresh();
                match t {
                    Ty::I8 | Ty::U8 => {
                        writeln!(self.out, "  %{} = sub i8 0, {}", tmp, v).unwrap();
                    }
                    Ty::I16 | Ty::U16 => {
                        writeln!(self.out, "  %{} = sub i16 0, {}", tmp, v).unwrap();
                    }
                    Ty::I32 => {
                        writeln!(self.out, "  %{} = sub nsw i32 0, {}", tmp, v).unwrap();
                    }
                    Ty::I64 | Ty::U64 | Ty::Isize | Ty::Usize => {
                        writeln!(self.out, "  %{} = sub i64 0, {}", tmp, v).unwrap();
                    }
                    Ty::I128 | Ty::U128 => {
                        writeln!(self.out, "  %{} = sub i128 0, {}", tmp, v).unwrap();
                    }
                    Ty::Array(_, _) | Ty::Struct(_) | Ty::Enum(_) | Ty::Unit | Ty::Ptr(_) | Ty::Bool => {
                        unreachable!("typechecked neg")
                    }
                }
                (t, format!("%{tmp}"))
            }
            Expr::Add(l, r) => {
                let (tl, vl) = self.emit_expr(l, locals, None);
                let (tr, vr) = self.emit_expr(r, locals, Some(&tl));
                assert!(types_match(&tl, &tr));
                let tmp = self.fresh();
                match tl {
                    Ty::I8 | Ty::U8 => {
                        writeln!(self.out, "  %{} = add i8 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I16 | Ty::U16 => {
                        writeln!(self.out, "  %{} = add i16 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I32 => {
                        writeln!(self.out, "  %{} = add nsw i32 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I64 | Ty::U64 | Ty::Isize | Ty::Usize => {
                        writeln!(self.out, "  %{} = add i64 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I128 | Ty::U128 => {
                        writeln!(self.out, "  %{} = add i128 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::Array(_, _) | Ty::Struct(_) | Ty::Enum(_) | Ty::Unit | Ty::Ptr(_) | Ty::Bool => {
                        unreachable!("add on non-numeric")
                    }
                }
                (tl, format!("%{tmp}"))
            }
            Expr::Sub(l, r) => {
                let (tl, vl) = self.emit_expr(l, locals, None);
                let (tr, vr) = self.emit_expr(r, locals, Some(&tl));
                assert!(types_match(&tl, &tr));
                let tmp = self.fresh();
                match tl {
                    Ty::I8 | Ty::U8 => {
                        writeln!(self.out, "  %{} = sub i8 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I16 | Ty::U16 => {
                        writeln!(self.out, "  %{} = sub i16 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I32 => {
                        writeln!(self.out, "  %{} = sub nsw i32 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I64 | Ty::U64 | Ty::Isize | Ty::Usize => {
                        writeln!(self.out, "  %{} = sub i64 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I128 | Ty::U128 => {
                        writeln!(self.out, "  %{} = sub i128 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::Array(_, _) | Ty::Struct(_) | Ty::Enum(_) | Ty::Unit | Ty::Ptr(_) | Ty::Bool => {
                        unreachable!("sub on non-numeric")
                    }
                }
                (tl, format!("%{tmp}"))
            }
            Expr::Mul(l, r) => {
                let (tl, vl) = self.emit_expr(l, locals, None);
                let (tr, vr) = self.emit_expr(r, locals, Some(&tl));
                assert!(types_match(&tl, &tr));
                let tmp = self.fresh();
                match tl {
                    Ty::I8 | Ty::U8 => {
                        writeln!(self.out, "  %{} = mul i8 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I16 | Ty::U16 => {
                        writeln!(self.out, "  %{} = mul i16 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I32 => {
                        writeln!(self.out, "  %{} = mul nsw i32 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I64 | Ty::U64 | Ty::Isize | Ty::Usize => {
                        writeln!(self.out, "  %{} = mul i64 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I128 | Ty::U128 => {
                        writeln!(self.out, "  %{} = mul i128 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::Array(_, _) | Ty::Struct(_) | Ty::Enum(_) | Ty::Unit | Ty::Ptr(_) | Ty::Bool => {
                        unreachable!("mul on non-numeric")
                    }
                }
                (tl, format!("%{tmp}"))
            }
            Expr::Div(l, r) => {
                let (tl, vl) = self.emit_expr(l, locals, None);
                let (tr, vr) = self.emit_expr(r, locals, Some(&tl));
                assert!(types_match(&tl, &tr));
                let tmp = self.fresh();
                let signed = int_ty_signed(&tl);
                match tl {
                    Ty::I8 | Ty::U8 => {
                        if signed {
                            writeln!(self.out, "  %{} = sdiv i8 {}, {}", tmp, vl, vr).unwrap();
                        } else {
                            writeln!(self.out, "  %{} = udiv i8 {}, {}", tmp, vl, vr).unwrap();
                        }
                    }
                    Ty::I16 | Ty::U16 => {
                        if signed {
                            writeln!(self.out, "  %{} = sdiv i16 {}, {}", tmp, vl, vr).unwrap();
                        } else {
                            writeln!(self.out, "  %{} = udiv i16 {}, {}", tmp, vl, vr).unwrap();
                        }
                    }
                    Ty::I32 => {
                        if signed {
                            writeln!(self.out, "  %{} = sdiv i32 {}, {}", tmp, vl, vr).unwrap();
                        } else {
                            writeln!(self.out, "  %{} = udiv i32 {}, {}", tmp, vl, vr).unwrap();
                        }
                    }
                    Ty::I64 | Ty::U64 | Ty::Isize | Ty::Usize => {
                        if signed {
                            writeln!(self.out, "  %{} = sdiv i64 {}, {}", tmp, vl, vr).unwrap();
                        } else {
                            writeln!(self.out, "  %{} = udiv i64 {}, {}", tmp, vl, vr).unwrap();
                        }
                    }
                    Ty::I128 | Ty::U128 => {
                        if signed {
                            writeln!(self.out, "  %{} = sdiv i128 {}, {}", tmp, vl, vr).unwrap();
                        } else {
                            writeln!(self.out, "  %{} = udiv i128 {}, {}", tmp, vl, vr).unwrap();
                        }
                    }
                    Ty::Array(_, _) | Ty::Struct(_) | Ty::Enum(_) | Ty::Unit | Ty::Ptr(_) | Ty::Bool => {
                        unreachable!("div on non-numeric")
                    }
                }
                (tl, format!("%{tmp}"))
            }
            Expr::Call { name, args } => {
                if name == PRINTLN {
                    let (at, av) = self.emit_expr(&args[0], locals, None);
                    self.emit_print_value(&at, &av, true);
                    return (Ty::Unit, String::new());
                }
                if name == ALLOC {
                    let (at, av) = self.emit_expr(&args[0], locals, None);
                    let sz = self.emit_sizeof_i64(&at);
                    let raw = self.fresh();
                    writeln!(self.out, "  %{} = call ptr @malloc(i64 {})", raw, sz).unwrap();
                    writeln!(
                        self.out,
                        "  store {} {}, ptr %{}",
                        llvm_ty(&at, self.structs),
                        av,
                        raw
                    )
                    .unwrap();
                    return (Ty::Ptr(Box::new(at)), format!("%{raw}"));
                }
                if name == DEALLOC {
                    let (_, pv) = self.emit_expr(&args[0], locals, None);
                    writeln!(self.out, "  call void @free(ptr {})", pv).unwrap();
                    return (Ty::Unit, String::new());
                }
                if name == REALLOC {
                    let (pt, pv) = self.emit_expr(&args[0], locals, None);
                    let Ty::Ptr(pointee) = pt else {
                        unreachable!("typechecked")
                    };
                    let (vt, vv) = self.emit_expr(&args[1], locals, Some(&pointee));
                    debug_assert!(types_match(&vt, &pointee));
                    let sz = self.emit_sizeof_i64(&pointee);
                    let raw = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = call ptr @realloc(ptr {}, i64 {})",
                        raw, pv, sz
                    )
                    .unwrap();
                    writeln!(
                        self.out,
                        "  store {} {}, ptr %{}",
                        llvm_ty(&pointee, self.structs),
                        vv,
                        raw
                    )
                    .unwrap();
                    return (Ty::Ptr(pointee), format!("%{raw}"));
                }
                if let Some(sdef) = self.structs.iter().find(|s| s.name == *name && s.is_tuple) {
                    let llvm_st = format!("%struct.{}", sanitize(name));
                    let mut agg = "poison".to_string();
                    for (i, (_, fty)) in sdef.fields.iter().enumerate() {
                        let (at, av) = self.emit_expr(&args[i], locals, Some(fty));
                        debug_assert!(types_match(&at, fty));
                        let tmp = self.fresh();
                        writeln!(
                            self.out,
                            "  %{} = insertvalue {} {}, {} {}, {}",
                            tmp,
                            llvm_st,
                            agg,
                            llvm_ty(&at, self.structs),
                            av,
                            i
                        )
                        .unwrap();
                        agg = format!("%{tmp}");
                    }
                    let sname = name.clone();
                    let tmp = self.fresh();
                    writeln!(self.out, "  %{} = alloca {}", tmp, llvm_st).unwrap();
                    writeln!(self.out, "  store {} {}, ptr %{}", llvm_st, agg, tmp).unwrap();
                    let loadt = self.fresh();
                    writeln!(self.out, "  %{} = load {}, ptr %{}", loadt, llvm_st, tmp).unwrap();
                    return (Ty::Struct(sname), format!("%{loadt}"));
                }
                let sig = self.fn_sigs.get(name).expect("unknown fn");
                let mut arg_strs = Vec::new();
                for (a, pt) in args.iter().zip(&sig.params) {
                    let (at, av) = self.emit_expr(a, locals, Some(pt));
                    debug_assert!(types_match(&at, pt));
                    arg_strs.push(format!("{} {}", llvm_ty(pt, self.structs), av));
                }
                match &sig.ret {
                    Some(ret_ty) => {
                        let tmp = self.fresh();
                        writeln!(
                            self.out,
                            "  %{} = call {} @{}({})",
                            tmp,
                            llvm_ty(ret_ty, self.structs),
                            sanitize(name),
                            arg_strs.join(", ")
                        )
                        .unwrap();
                        (ret_ty.clone(), format!("%{tmp}"))
                    }
                    None => {
                        writeln!(
                            self.out,
                            "  call void @{}({})",
                            sanitize(name),
                            arg_strs.join(", ")
                        )
                        .unwrap();
                        (Ty::Unit, String::new())
                    }
                }
            }
            Expr::StructLit { name, fields } => {
                let sdef = self.structs.iter().find(|s| s.name == *name).unwrap();
                let llvm_st = format!("%struct.{}", sanitize(name));
                let mut agg = "poison".to_string();
                for (i, (fname, _)) in sdef.fields.iter().enumerate() {
                    let (_, fe) = fields.iter().find(|(n, _)| n == fname).unwrap();
                    let fty = sdef.fields[i].1.clone();
                    let (ft, fv) = self.emit_expr(fe, locals, Some(&fty));
                    let tmp = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = insertvalue {} {}, {} {}, {}",
                        tmp,
                        llvm_st,
                        agg,
                        llvm_ty(&ft, self.structs),
                        fv,
                        i
                    )
                    .unwrap();
                    agg = format!("%{tmp}");
                }
                let sname = name.clone();
                let tmp = self.fresh();
                writeln!(self.out, "  %{} = alloca {}", tmp, llvm_st).unwrap();
                writeln!(self.out, "  store {} {}, ptr %{}", llvm_st, agg, tmp).unwrap();
                let loadt = self.fresh();
                writeln!(self.out, "  %{} = load {}, ptr %{}", loadt, llvm_st, tmp).unwrap();
                (Ty::Struct(sname), format!("%{loadt}"))
            }
            Expr::EnumVariant { enum_name, variant } => {
                let tag = self.enum_tag(enum_name, variant).expect("typechecked enum variant");
                let enum_ll = format!("%enum.{}", sanitize(enum_name));
                let idx = self
                    .enum_variant_index(enum_name, variant)
                    .expect("typechecked enum idx");
                let vdef = self
                    .enum_variant_def(enum_name, variant)
                    .expect("typechecked enum variant")
                    .clone();
                let payload_ll = enum_variant_payload_ty(&vdef, self.structs);
                let with_tag = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = insertvalue {} poison, i32 {}, 0",
                    with_tag, enum_ll, tag
                )
                .unwrap();
                let with_payload = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = insertvalue {} %{}, {} zeroinitializer, {}",
                    with_payload,
                    enum_ll,
                    with_tag,
                    payload_ll,
                    idx + 1
                )
                .unwrap();
                (Ty::Enum(enum_name.clone()), format!("%{with_payload}"))
            }
            Expr::EnumTuple {
                enum_name,
                variant,
                args,
            } => {
                let tag = self.enum_tag(enum_name, variant).expect("typechecked enum variant");
                let idx = self
                    .enum_variant_index(enum_name, variant)
                    .expect("typechecked enum idx");
                let vdef = self
                    .enum_variant_def(enum_name, variant)
                    .expect("typechecked enum variant")
                    .clone();
                let EnumVariantFields::Tuple(ts) = vdef.fields else {
                    unreachable!("typechecked tuple variant")
                };
                let enum_ll = format!("%enum.{}", sanitize(enum_name));
                let with_tag = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = insertvalue {} poison, i32 {}, 0",
                    with_tag, enum_ll, tag
                )
                .unwrap();
                let payload_val = if ts.len() == 1 {
                    let (_, v) = self.emit_expr(&args[0], locals, Some(&ts[0]));
                    (llvm_ty(&ts[0], self.structs), v)
                } else {
                    let payload_ll = if ts.len() == 1 {
                        llvm_ty(&ts[0], self.structs)
                    } else {
                        let inner = ts
                            .iter()
                            .map(|t| llvm_ty(t, self.structs))
                            .collect::<Vec<_>>()
                            .join(", ");
                        format!("{{ {inner} }}")
                    };
                    let mut agg = "poison".to_string();
                    for (i, (a, t)) in args.iter().zip(ts.iter()).enumerate() {
                        let (_, av) = self.emit_expr(a, locals, Some(t));
                        let tmp = self.fresh();
                        writeln!(
                            self.out,
                            "  %{} = insertvalue {} {}, {} {}, {}",
                            tmp,
                            payload_ll,
                            agg,
                            llvm_ty(t, self.structs),
                            av,
                            i
                        )
                        .unwrap();
                        agg = format!("%{tmp}");
                    }
                    (payload_ll, agg)
                };
                let out = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = insertvalue {} %{}, {} {}, {}",
                    out,
                    enum_ll,
                    with_tag,
                    payload_val.0,
                    payload_val.1,
                    idx + 1
                )
                .unwrap();
                (Ty::Enum(enum_name.clone()), format!("%{out}"))
            }
            Expr::EnumStruct {
                enum_name,
                variant,
                fields,
            } => {
                let tag = self.enum_tag(enum_name, variant).expect("typechecked enum variant");
                let idx = self
                    .enum_variant_index(enum_name, variant)
                    .expect("typechecked enum idx");
                let vdef = self
                    .enum_variant_def(enum_name, variant)
                    .expect("typechecked enum variant")
                    .clone();
                let EnumVariantFields::Struct(fs) = vdef.fields else {
                    unreachable!("typechecked struct variant")
                };
                let enum_ll = format!("%enum.{}", sanitize(enum_name));
                let with_tag = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = insertvalue {} poison, i32 {}, 0",
                    with_tag, enum_ll, tag
                )
                .unwrap();
                let payload_ll = {
                    let inner = fs
                        .iter()
                        .map(|(_, t)| llvm_ty(t, self.structs))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{{ {inner} }}")
                };
                let mut agg = "poison".to_string();
                for (i, (fname, fty)) in fs.iter().enumerate() {
                    let (_, fe) = fields.iter().find(|(n, _)| n == fname).expect("typechecked");
                    let (_, fv) = self.emit_expr(fe, locals, Some(fty));
                    let tmp = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = insertvalue {} {}, {} {}, {}",
                        tmp,
                        payload_ll,
                        agg,
                        llvm_ty(fty, self.structs),
                        fv,
                        i
                    )
                    .unwrap();
                    agg = format!("%{tmp}");
                }
                let out = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = insertvalue {} %{}, {} {}, {}",
                    out,
                    enum_ll,
                    with_tag,
                    payload_ll,
                    agg,
                    idx + 1
                )
                .unwrap();
                (Ty::Enum(enum_name.clone()), format!("%{out}"))
            }
            Expr::Match { scrutinee, arms } => {
                let (st, sv) = self.emit_expr(scrutinee, locals, None);
                let Ty::Enum(enum_name) = st else {
                    unreachable!("typechecked match enum")
                };
                let tag_tmp = self.fresh();
                let enum_ll = format!("%enum.{}", sanitize(&enum_name));
                writeln!(
                    self.out,
                    "  %{} = extractvalue {} {}, 0",
                    tag_tmp, enum_ll, sv
                )
                .unwrap();
                let cont_lbl = self.fresh_label("match.cont");
                let default_lbl = self.fresh_label("match.default");
                let mut arm_labels = Vec::new();
                for _ in arms {
                    arm_labels.push(self.fresh_label("match.arm"));
                }
                writeln!(self.out, "  switch i32 %{}, label %{} [", tag_tmp, default_lbl).unwrap();
                for ((pat, _), lbl) in arms.iter().zip(&arm_labels) {
                    let variant = match pat {
                        MatchPattern::Unit { variant, .. } => variant,
                        MatchPattern::Tuple { variant, .. } => variant,
                        MatchPattern::Struct { variant, .. } => variant,
                    };
                    let tag = self.enum_tag(&enum_name, variant).expect("typechecked enum tag");
                    writeln!(self.out, "    i32 {}, label %{}", tag, lbl).unwrap();
                }
                writeln!(self.out, "  ]").unwrap();
                writeln!(self.out, "{}:", default_lbl).unwrap();
                writeln!(self.out, "  unreachable").unwrap();

                let mut arm_vals: Vec<(String, String)> = Vec::new();
                let mut out_ty: Option<Ty> = None;
                for ((pat, arm_expr), lbl) in arms.iter().zip(&arm_labels) {
                    writeln!(self.out, "{}:", lbl).unwrap();
                    let mut arm_locals = locals.clone();
                    let variant = match pat {
                        MatchPattern::Unit { variant, .. } => variant,
                        MatchPattern::Tuple { variant, .. } => variant,
                        MatchPattern::Struct { variant, .. } => variant,
                    };
                    let vidx = self
                        .enum_variant_index(&enum_name, variant)
                        .expect("typechecked enum idx");
                    let vdef = self
                        .enum_variant_def(&enum_name, variant)
                        .expect("typechecked enum variant")
                        .clone();
                    match (pat, vdef.fields) {
                        (MatchPattern::Unit { .. }, EnumVariantFields::Unit) => {}
                        (
                            MatchPattern::Tuple { bindings, .. },
                            EnumVariantFields::Tuple(ts),
                        ) => {
                            let payload_ll = if ts.len() == 1 {
                                llvm_ty(&ts[0], self.structs)
                            } else {
                                let inner = ts
                                    .iter()
                                    .map(|t| llvm_ty(t, self.structs))
                                    .collect::<Vec<_>>()
                                    .join(", ");
                                format!("{{ {inner} }}")
                            };
                            let pl = self.fresh();
                            writeln!(
                                self.out,
                                "  %{} = extractvalue {} {}, {}",
                                pl, enum_ll, sv, vidx + 1
                            )
                            .unwrap();
                            if ts.len() == 1 {
                                let ptr = format!("%{}.addr", sanitize(&bindings[0]));
                                writeln!(
                                    self.out,
                                    "  {} = alloca {}",
                                    ptr,
                                    llvm_ty(&ts[0], self.structs)
                                )
                                .unwrap();
                                writeln!(
                                    self.out,
                                    "  store {} %{}, ptr {}",
                                    llvm_ty(&ts[0], self.structs),
                                    pl,
                                    ptr
                                )
                                .unwrap();
                                arm_locals.insert(bindings[0].clone(), (ts[0].clone(), ptr));
                            } else {
                                for (i, (b, t)) in bindings.iter().zip(ts.iter()).enumerate() {
                                    let ev = self.fresh();
                                    writeln!(
                                        self.out,
                                        "  %{} = extractvalue {} %{}, {}",
                                        ev, payload_ll, pl, i
                                    )
                                    .unwrap();
                                    let ptr = format!("%{}.addr", sanitize(b));
                                    writeln!(
                                        self.out,
                                        "  {} = alloca {}",
                                        ptr,
                                        llvm_ty(t, self.structs)
                                    )
                                    .unwrap();
                                    writeln!(
                                        self.out,
                                        "  store {} %{}, ptr {}",
                                        llvm_ty(t, self.structs),
                                        ev,
                                        ptr
                                    )
                                    .unwrap();
                                    arm_locals.insert(b.clone(), (t.clone(), ptr));
                                }
                            }
                        }
                        (
                            MatchPattern::Struct { bindings, .. },
                            EnumVariantFields::Struct(fs),
                        ) => {
                            let payload_ll = {
                                let inner = fs
                                    .iter()
                                    .map(|(_, t)| llvm_ty(t, self.structs))
                                    .collect::<Vec<_>>()
                                    .join(", ");
                                format!("{{ {inner} }}")
                            };
                            let pl = self.fresh();
                            writeln!(
                                self.out,
                                "  %{} = extractvalue {} {}, {}",
                                pl, enum_ll, sv, vidx + 1
                            )
                            .unwrap();
                            for b in bindings {
                                let (i, (_, t)) = fs
                                    .iter()
                                    .enumerate()
                                    .find(|(_, (n, _))| n == b)
                                    .expect("typechecked field");
                                let ev = self.fresh();
                                writeln!(
                                    self.out,
                                    "  %{} = extractvalue {} %{}, {}",
                                    ev, payload_ll, pl, i
                                )
                                .unwrap();
                                let ptr = format!("%{}.addr", sanitize(b));
                                writeln!(self.out, "  {} = alloca {}", ptr, llvm_ty(t, self.structs))
                                    .unwrap();
                                writeln!(
                                    self.out,
                                    "  store {} %{}, ptr {}",
                                    llvm_ty(t, self.structs),
                                    ev,
                                    ptr
                                )
                                .unwrap();
                                arm_locals.insert(b.clone(), (t.clone(), ptr));
                            }
                        }
                        _ => unreachable!("typechecked pattern kind"),
                    }
                    let (at, av) = self.emit_expr(arm_expr, &arm_locals, hint);
                    if !matches!(at, Ty::Unit) {
                        arm_vals.push((av.clone(), lbl.clone()));
                    }
                    if out_ty.is_none() {
                        out_ty = Some(at.clone());
                    }
                    writeln!(self.out, "  br label %{}", cont_lbl).unwrap();
                }
                writeln!(self.out, "{}:", cont_lbl).unwrap();
                let out_ty = out_ty.expect("typechecked non-empty match");
                if matches!(out_ty, Ty::Unit) {
                    (Ty::Unit, String::new())
                } else {
                    let phi = self.fresh();
                    let ll = llvm_ty(&out_ty, self.structs);
                    let incoming = arm_vals
                        .iter()
                        .map(|(v, l)| format!("[ {}, %{} ]", v, l))
                        .collect::<Vec<_>>()
                        .join(", ");
                    writeln!(self.out, "  %{} = phi {} {}", phi, ll, incoming).unwrap();
                    (out_ty, format!("%{phi}"))
                }
            }
            Expr::ArrayLit(elems) => {
                let (elem_ty, n) = match hint {
                    Some(Ty::Array(elem, n)) => (elem.as_ref().clone(), *n),
                    _ => {
                        let first = elems.first().expect("typechecked non-empty array");
                        let (t, _) = self.emit_expr(first, locals, None);
                        (t, elems.len())
                    }
                };
                let llvm_arr = format!("[{} x {}]", n, llvm_ty(&elem_ty, self.structs));
                let mut agg = "poison".to_string();
                for (i, e) in elems.iter().enumerate() {
                    let (et, ev) = self.emit_expr(e, locals, Some(&elem_ty));
                    debug_assert!(types_match(&et, &elem_ty));
                    let tmp = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = insertvalue {} {}, {} {}, {}",
                        tmp,
                        llvm_arr,
                        agg,
                        llvm_ty(&et, self.structs),
                        ev,
                        i
                    )
                    .unwrap();
                    agg = format!("%{tmp}");
                }
                let tmp = self.fresh();
                writeln!(self.out, "  %{} = alloca {}", tmp, llvm_arr).unwrap();
                writeln!(self.out, "  store {} {}, ptr %{}", llvm_arr, agg, tmp).unwrap();
                let loadt = self.fresh();
                writeln!(self.out, "  %{} = load {}, ptr %{}", loadt, llvm_arr, tmp).unwrap();
                (Ty::Array(Box::new(elem_ty), n), format!("%{loadt}"))
            }
            Expr::Field(obj, fname) => {
                let (bt, bv) = self.emit_expr(obj, locals, None);
                let Ty::Struct(sname) = bt else {
                    unreachable!()
                };
                let idx = self.struct_idx(&sname, fname).unwrap();
                let llvm_st = format!("%struct.{}", sanitize(&sname));
                let tmp = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = extractvalue {} {}, {}",
                    tmp, llvm_st, bv, idx
                )
                .unwrap();
                let fty = self
                    .structs
                    .iter()
                    .find(|s| s.name == sname)
                    .unwrap()
                    .fields
                    .iter()
                    .find(|(n, _)| n == fname)
                    .unwrap()
                    .1
                    .clone();
                (fty, format!("%{tmp}"))
            }
            Expr::Index(arr, idx) => {
                let full = Expr::Index(arr.clone(), idx.clone());
                if let Some((name, idxs)) = collect_array_index_chain(&full) {
                    let (elem_ty, gep_ptr) =
                        self.emit_array_gep_chain(&name, &idxs, locals);
                    let val = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = load {}, ptr {}",
                        val,
                        llvm_ty(&elem_ty, self.structs),
                        gep_ptr
                    )
                    .unwrap();
                    (elem_ty, format!("%{val}"))
                } else {
                    let (at, av) = self.emit_expr(arr, locals, None);
                    let (it, iv) = self.emit_expr(idx, locals, Some(&Ty::I32));
                    debug_assert!(matches!(it, Ty::I32));
                    let Ty::Array(elem_ty, n) = at else {
                        unreachable!("typechecked")
                    };
                    let llvm_arr = format!("[{} x {}]", n, llvm_ty(&elem_ty, self.structs));
                    let ptr = self.fresh();
                    writeln!(self.out, "  %{} = alloca {}", ptr, llvm_arr).unwrap();
                    writeln!(self.out, "  store {} {}, ptr %{}", llvm_arr, av, ptr).unwrap();
                    let idx64 = self.fresh();
                    writeln!(self.out, "  %{} = sext i32 {} to i64", idx64, iv).unwrap();
                    let gep = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = getelementptr inbounds {}, ptr %{}, i64 0, i64 %{}",
                        gep, llvm_arr, ptr, idx64
                    )
                    .unwrap();
                    let val = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = load {}, ptr %{}",
                        val,
                        llvm_ty(&elem_ty, self.structs),
                        gep
                    )
                    .unwrap();
                    ((*elem_ty).clone(), format!("%{val}"))
                }
            }
            Expr::AddrOf(inner) => {
                let Expr::Ident(name) = inner.as_ref() else {
                    unreachable!("typechecked")
                };
                let (ty, ptr) = locals.get(name).expect("checked var");
                (Ty::Ptr(Box::new(ty.clone())), ptr.clone())
            }
            Expr::Deref(inner) => {
                let (ti, v) = self.emit_expr(inner, locals, None);
                let Ty::Ptr(pointee) = ti else {
                    unreachable!("typechecked")
                };
                let tmp = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = load {}, ptr {}",
                    tmp,
                    llvm_ty(pointee.as_ref(), self.structs),
                    v
                )
                .unwrap();
                ((*pointee).clone(), format!("%{tmp}"))
            }
        }
    }

    /// Follow `name` through `indices` with GEP; returns element type and `ptr` to the slot.
    fn emit_array_gep_chain(
        &mut self,
        name: &str,
        indices: &[&Expr],
        locals: &HashMap<String, (Ty, String)>,
    ) -> (Ty, String) {
        let (mut cur_ty, mut llvm_ptr) = locals.get(name).expect("indexed assign var").clone();
        for idx_expr in indices {
            let Ty::Array(elem_ty, n) = &cur_ty else {
                unreachable!("typechecked index chain");
            };
            let (_, iv) = self.emit_expr(idx_expr, locals, Some(&Ty::I32));
            let llvm_arr = format!("[{} x {}]", n, llvm_ty(elem_ty, self.structs));
            let idx64 = self.fresh();
            writeln!(self.out, "  %{} = sext i32 {} to i64", idx64, iv).unwrap();
            let gep = self.fresh();
            writeln!(
                self.out,
                "  %{} = getelementptr inbounds {}, ptr {}, i64 0, i64 %{}",
                gep, llvm_arr, llvm_ptr, idx64
            )
            .unwrap();
            llvm_ptr = format!("%{gep}");
            cur_ty = *elem_ty.clone();
        }
        (cur_ty, llvm_ptr)
    }

    fn emit_assign_ptr(
        &mut self,
        target: &Expr,
        locals: &HashMap<String, (Ty, String)>,
    ) -> (Ty, String) {
        match target {
            Expr::Ident(name) => {
                let (ty, ptr) = locals.get(name).expect("typechecked assign ident");
                (ty.clone(), ptr.clone())
            }
            Expr::Deref(inner) => {
                let (pt, pv) = self.emit_expr(inner, locals, None);
                let Ty::Ptr(pointee) = pt else {
                    unreachable!("typechecked assign deref")
                };
                ((*pointee).clone(), pv)
            }
            Expr::Index(arr, idx) => {
                let full = Expr::Index(arr.clone(), idx.clone());
                if let Some((name, idxs)) = collect_array_index_chain(&full) {
                    self.emit_array_gep_chain(&name, &idxs, locals)
                } else {
                    unreachable!("typechecked indexed assign")
                }
            }
            _ => unreachable!("typechecked assign lvalue"),
        }
    }
}

/// Lightweight type compatibility used by codegen assertions.
fn types_match(a: &Ty, b: &Ty) -> bool {
    match (a, b) {
        (Ty::I8, Ty::I8)
        | (Ty::U8, Ty::U8)
        | (Ty::I16, Ty::I16)
        | (Ty::U16, Ty::U16)
        | (Ty::I32, Ty::I32)
        | (Ty::I64, Ty::I64)
        | (Ty::U64, Ty::U64)
        | (Ty::I128, Ty::I128)
        | (Ty::Isize, Ty::Isize)
        | (Ty::Usize, Ty::Usize)
        | (Ty::U128, Ty::U128)
        | (Ty::Bool, Ty::Bool)
        | (Ty::Unit, Ty::Unit) => true,
        (Ty::Array(ax, an), Ty::Array(bx, bn)) => an == bn && types_match(ax, bx),
        (Ty::Struct(x), Ty::Struct(y)) => x == y,
        (Ty::Enum(x), Ty::Enum(y)) => x == y,
        (Ty::Ptr(x), Ty::Ptr(y)) => types_match(x, y),
        _ => false,
    }
}

/// Convenience wrapper creating fresh generator per function.
fn emit_fn(f: &FnDef, structs: &[StructDef], enums: &[EnumDef], fn_sigs: &HashMap<String, FnSig>) -> String {
    Gen::new(structs, enums, fn_sigs).emit_fn(f)
}

#[cfg(test)]
mod tests;
