//! Default pipeline smoke tests (same path as `compile_to_ll`).

use crate::driver::fixtures::{read_fixture, TIER_0, TIER_1};

fn compile_new_fixture_ok(path: &str) {
    let src = read_fixture(path);
    let ll = crate::driver::pipeline::compile_new_to_ll(&src)
        .unwrap_or_else(|e| panic!("new pipeline failed for `{path}`: {e}"));
    assert!(ll.contains("generated by nialang (new pipeline)"));
    assert!(ll.contains("define i32 @main("), "{path} missing main");
}

#[test]
fn tier_0_fixtures_compile_via_new_pipeline() {
    for path in TIER_0 {
        compile_new_fixture_ok(path);
    }
}

#[test]
fn tier_1_fixtures_compile_via_new_pipeline() {
    for path in TIER_1 {
        compile_new_fixture_ok(path);
    }
}

#[test]
fn tier_2_subset_fixtures_compile_via_new_pipeline() {
    for path in [
        "examples/tests/ok_floats.nia",
        "examples/tests/ok_string.nia",
        "examples/tests/ok_impl_methods.nia",
        "examples/tests/ok_print_structs.nia",
        "examples/tests/ok_print_array.nia",
        "examples/tests/ok_vector_to_array.nia",
        "examples/tests/ok_array_to_vec.nia",
        "examples/tests/ok_gpu_scope.nia",
        "examples/tests/ok_quant_scope.nia",
        "examples/tests/ok_array_matrix_conversions.nia",
    ] {
        compile_new_fixture_ok(path);
    }
}
