//! LLVM IR backend for the new pipeline (phase 8.4).

use std::fmt::Write as _;

use crate::elab::{BinOp, CmpOp, RuntimeTy};
use crate::erase::{ErasedArm, ErasedExpr, ErasedFn};
use crate::frontend::surface::{EnumDef, EnumVariantFields, StructDef};
use crate::hir::ClassicalModule;

pub fn emit_module(module: &ClassicalModule) -> String {
    let mut out = String::new();
    out.push_str("; generated by nialang (new pipeline)\n");
    out.push_str(
        "target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\"\n",
    );
    out.push_str("target triple = \"unknown-unknown-unknown\"\n\n");
    out.push_str(crate::nia_std::llvm_prelude());

    let structs: Vec<StructDef> = module
        .resolved
        .structs
        .iter()
        .filter(|s| !s.is_builtin)
        .map(|s| s.def.clone())
        .collect();
    let enums: Vec<EnumDef> = module.resolved.enums.iter().map(|e| e.def.clone()).collect();

    out.push_str(&emit_enum_print_constants(&enums));
    out.push_str(&emit_struct_print_constants(&structs));
    if !module.erased.strings.is_empty() {
        out.push_str(&emit_string_literals(&module.erased.strings));
        out.push_str(STRCMP_DEF);
        out.push('\n');
    }
    for s in &structs {
        out.push_str(&struct_type_decl(s));
        out.push('\n');
    }
    for e in &enums {
        out.push_str(&enum_type_decl(e, &structs));
        out.push('\n');
    }
    if !structs.is_empty() || !enums.is_empty() {
        out.push('\n');
    }

    let fn_rets = &module.erased.symbols.fn_rets;
    let strings = &module.erased.strings;
    for f in &module.erased.fns {
        out.push_str(&emit_fn(f, &structs, &enums, fn_rets, strings));
        out.push('\n');
    }
    out
}

struct Emitter<'a> {
    out: String,
    fresh: u32,
    structs: &'a [StructDef],
    enums: &'a [EnumDef],
    fn_rets: &'a std::collections::HashMap<String, RuntimeTy>,
    strings: &'a [String],
    terminated: bool,
    loop_exit_stack: Vec<String>,
}

impl<'a> Emitter<'a> {
    fn new(
        structs: &'a [StructDef],
        enums: &'a [EnumDef],
        fn_rets: &'a std::collections::HashMap<String, RuntimeTy>,
        strings: &'a [String],
    ) -> Self {
        Self {
            out: String::new(),
            fresh: 0,
            structs,
            enums,
            fn_rets,
            strings,
            terminated: false,
            loop_exit_stack: Vec::new(),
        }
    }

    fn fn_ret(&self, name: &str) -> Option<RuntimeTy> {
        self.fn_rets.get(name).cloned()
    }

    fn fresh(&mut self) -> String {
        let n = self.fresh;
        self.fresh += 1;
        format!("t{n}")
    }

    fn fresh_label(&mut self, prefix: &str) -> String {
        let n = self.fresh;
        self.fresh += 1;
        format!("{prefix}.{n}")
    }

    fn emit_fn(mut self, f: &ErasedFn) -> String {
        self.out.clear();
        let ret_ll = llvm_ty(&f.ret, self.structs, self.enums);
        let params: Vec<String> = f
            .params
            .iter()
            .map(|(name, ty)| format!("{} %{}", llvm_ty(ty, self.structs, self.enums), sanitize(name)))
            .collect();
        let linkage = if f.name == "main" { "" } else { "internal " };
        writeln!(
            self.out,
            "define {}{} @{}({}) {{",
            linkage,
            ret_ll,
            sanitize(&f.name),
            params.join(", ")
        )
        .unwrap();
        writeln!(self.out, "entry:").unwrap();

        let mut slots: Vec<(RuntimeTy, String)> = Vec::new();
        for (name, ty) in &f.params {
            let ll = llvm_ty(ty, self.structs, self.enums);
            let ps = sanitize(name);
            let ptr = format!("%{ps}.addr");
            writeln!(self.out, "  {ptr} = alloca {ll}").unwrap();
            writeln!(self.out, "  store {ll} %{ps}, ptr {ptr}").unwrap();
            slots.push((ty.clone(), ptr));
        }

        let (rt, val) = self.emit_expr(&f.body, &mut slots, Some(&f.ret));
        debug_assert_eq!(rt, f.ret);
        writeln!(self.out, "  ret {ret_ll} {val}").unwrap();
        writeln!(self.out, "}}").unwrap();
        self.out
    }

    fn emit_expr(
        &mut self,
        expr: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
        expected: Option<&RuntimeTy>,
    ) -> (RuntimeTy, String) {
        match expr {
            ErasedExpr::LitI32(n) => (RuntimeTy::I32, format!("{n}")),
            ErasedExpr::LitBool(b) => {
                (RuntimeTy::Bool, if *b { "1" } else { "0" }.to_string())
            }
            ErasedExpr::LitInt { value, ty } => {
                let lit = truncate_int(*value, ty);
                (ty.clone(), lit)
            }
            ErasedExpr::LitFloat { value, ty } => {
                let lit = format_float_literal(*value, ty);
                (ty.clone(), lit)
            }
            ErasedExpr::LitStr(idx) => {
                let len = self.strings[*idx as usize].len() + 1;
                let sym = format!("@nialang.strlit.{idx}");
                let dst = self.fresh();
                writeln!(
                    self.out,
                    "  %{dst} = getelementptr inbounds [{len} x i8], ptr {sym}, i64 0, i64 0"
                )
                .unwrap();
                (RuntimeTy::String, format!("%{dst}"))
            }
            ErasedExpr::StrEq(l, r) => {
                let (lt, lv) = self.emit_expr(l, slots, Some(&RuntimeTy::String));
                let (rt, rv) = self.emit_expr(r, slots, Some(&RuntimeTy::String));
                assert_eq!(lt, RuntimeTy::String);
                assert_eq!(rt, RuntimeTy::String);
                let cmp = self.fresh();
                writeln!(
                    self.out,
                    "  %{cmp} = call i32 @strcmp(ptr {lv}, ptr {rv})"
                )
                .unwrap();
                let dst = self.fresh();
                writeln!(self.out, "  %{dst} = icmp eq i32 %{cmp}, 0").unwrap();
                (RuntimeTy::Bool, format!("%{dst}"))
            }
            ErasedExpr::Unit => (RuntimeTy::Unit, "0".into()),
            ErasedExpr::Var(level) => self.load_slot(slots, *level),
            ErasedExpr::Let { value, body } => {
                let (ty, val) = self.emit_expr(value, slots, None);
                let ptr = format!("%let.{}", self.fresh());
                let ll = llvm_ty(&ty, self.structs, self.enums);
                writeln!(self.out, "  {ptr} = alloca {ll}").unwrap();
                writeln!(self.out, "  store {ll} {val}, ptr {ptr}").unwrap();
                slots.push((ty, ptr));
                let out = self.emit_expr(body, slots, expected);
                slots.pop();
                out
            }
            ErasedExpr::CallFn(name, args) => {
                let mut arg_vals = Vec::new();
                let mut arg_tys = Vec::new();
                for arg in args {
                    let (t, v) = self.emit_expr(arg, slots, None);
                    arg_tys.push(t);
                    arg_vals.push(v);
                }
                let ret_ty = expected
                    .cloned()
                    .or_else(|| self.fn_ret(name))
                    .unwrap_or(RuntimeTy::I32);
                let ret_ll = llvm_ty(&ret_ty, self.structs, self.enums);
                let call_args: Vec<String> = arg_tys
                    .iter()
                    .zip(&arg_vals)
                    .map(|(t, v)| format!("{} {v}", llvm_ty(t, self.structs, self.enums)))
                    .collect();
                let dst = self.fresh();
                writeln!(
                    self.out,
                    "  %{dst} = call {ret_ll} @{}({})",
                    sanitize(name),
                    call_args.join(", ")
                )
                .unwrap();
                (ret_ty, format!("%{dst}"))
            }
            ErasedExpr::Cmp(op, ty, l, r) => {
                let (lt, lv) = self.emit_expr(l, slots, Some(ty));
                let (rt, rv) = self.emit_expr(r, slots, Some(ty));
                assert_eq!(lt, *ty);
                assert_eq!(rt, *ty);
                let dst = self.fresh();
                let ll = llvm_ty(ty, self.structs, self.enums);
                if is_float_ty(ty) {
                    let inst = float_cmp_inst(*op);
                    writeln!(self.out, "  %{dst} = {inst} {ll} {lv}, {rv}").unwrap();
                } else {
                    let signed = matches!(
                        ty,
                        RuntimeTy::I8 | RuntimeTy::I16 | RuntimeTy::I32 | RuntimeTy::I64 | RuntimeTy::I128
                    );
                    let inst = match (op, signed) {
                        (CmpOp::Lt, true) => "icmp slt",
                        (CmpOp::Lt, false) => "icmp ult",
                        (CmpOp::Gt, true) => "icmp sgt",
                        (CmpOp::Gt, false) => "icmp ugt",
                    };
                    writeln!(self.out, "  %{dst} = {inst} {ll} {lv}, {rv}").unwrap();
                }
                (RuntimeTy::Bool, format!("%{dst}"))
            }
            ErasedExpr::BinOp(op, ty, l, r) => {
                let (lt, lv) = self.emit_expr(l, slots, Some(ty));
                let (rt, rv) = self.emit_expr(r, slots, Some(ty));
                assert_eq!(lt, *ty);
                assert_eq!(rt, *ty);
                let dst = self.fresh();
                let ll = llvm_ty(ty, self.structs, self.enums);
                let inst = if is_float_ty(ty) {
                    float_binop_inst(*op)
                } else {
                    int_binop_inst(*op, ty)
                };
                writeln!(self.out, "  %{dst} = {inst} {ll} {lv}, {rv}").unwrap();
                (ty.clone(), format!("%{dst}"))
            }
            ErasedExpr::If(ty, cond, then_br, else_br) => {
                let (_, cv) = self.emit_expr(cond, slots, Some(&RuntimeTy::Bool));
                let then_lbl = self.fresh_label("if.then");
                let else_lbl = self.fresh_label("if.else");
                let merge_lbl = self.fresh_label("if.merge");
                let dst = self.fresh();
                let ll = llvm_ty(ty, self.structs, self.enums);
                writeln!(
                    self.out,
                    "  br i1 {cv}, label %{then_lbl}, label %{else_lbl}"
                )
                .unwrap();

                writeln!(self.out, "{then_lbl}:").unwrap();
                let (_, tv) = self.emit_expr(then_br, slots, Some(ty));
                writeln!(self.out, "  br label %{merge_lbl}").unwrap();

                writeln!(self.out, "{else_lbl}:").unwrap();
                let (_, ev) = self.emit_expr(else_br, slots, Some(ty));
                writeln!(self.out, "  br label %{merge_lbl}").unwrap();

                writeln!(self.out, "{merge_lbl}:").unwrap();
                writeln!(
                    self.out,
                    "  %{dst} = phi {ll} [{tv}, %{then_lbl}], [{ev}, %{else_lbl}]"
                )
                .unwrap();
                (ty.clone(), format!("%{dst}"))
            }
            ErasedExpr::Println(ty, arg) => {
                let (at, av) = self.emit_expr(arg, slots, Some(ty));
                assert_eq!(&at, ty);
                self.emit_println(ty, &av, true);
                (RuntimeTy::Unit, "0".into())
            }
            ErasedExpr::StructAgg { name, fields } => {
                let sdef = self
                    .structs
                    .iter()
                    .find(|s| s.name == *name)
                    .expect("struct decl");
                let llvm_st = format!("%struct.{}", sanitize(name));
                let mut cur = format!("zeroinitializer");
                for (i, field) in fields.iter().enumerate() {
                    let (fty, fv) = self.emit_expr(
                        field,
                        slots,
                        Some(&surface_field_ty(sdef, i)),
                    );
                    let fll = llvm_ty(&fty, self.structs, self.enums);
                    let tmp = self.fresh();
                    writeln!(
                        self.out,
                        "  %{tmp} = insertvalue {llvm_st} {cur}, {fll} {fv}, {i}"
                    )
                    .unwrap();
                    cur = format!("%{tmp}");
                }
                (RuntimeTy::Struct(name.clone()), cur)
            }
            ErasedExpr::FieldGet {
                struct_name,
                value,
                index,
            } => {
                let (sty, sv) = self.emit_expr(value, slots, None);
                let sdef = self
                    .structs
                    .iter()
                    .find(|s| s.name == *struct_name)
                    .expect("struct decl");
                let fty = surface_field_ty(sdef, *index as usize);
                let llvm_st = format!("%struct.{}", sanitize(struct_name));
                let dst = self.fresh();
                writeln!(
                    self.out,
                    "  %{dst} = extractvalue {llvm_st} {sv}, {index}"
                )
                .unwrap();
                (fty, format!("%{dst}"))
            }
            ErasedExpr::EnumAgg { name, variant, args } => {
                let edef = self
                    .enums
                    .iter()
                    .find(|e| e.name == *name)
                    .expect("enum decl");
                let llvm_en = format!("%enum.{}", sanitize(name));
                let mut cur = format!("insertvalue {llvm_en} undef, i32 {variant}, 0");
                let payload_idx = *variant as usize + 1;
                let vdef = &edef.variants[*variant as usize];
                match &vdef.fields {
                    EnumVariantFields::Unit => {}
                    EnumVariantFields::Tuple(ts) if ts.len() == 1 => {
                        let (aty, av) = self.emit_expr(
                            &args[0],
                            slots,
                            Some(&runtime_ty_from_surface(&ts[0])),
                        );
                        let all = llvm_ty(&aty, self.structs, self.enums);
                        let tmp = self.fresh();
                        writeln!(
                            self.out,
                            "  %{tmp} = insertvalue {cur}, {all} {av}, {payload_idx}"
                        )
                        .unwrap();
                        cur = format!("%{tmp}");
                    }
                    EnumVariantFields::Tuple(ts) => {
                        let mut agg = "undef".to_string();
                        for (i, (arg, sty)) in args.iter().zip(ts.iter()).enumerate() {
                            let (aty, av) =
                                self.emit_expr(arg, slots, Some(&runtime_ty_from_surface(sty)));
                            let all = llvm_ty(&aty, self.structs, self.enums);
                            let tmp = self.fresh();
                            writeln!(
                                self.out,
                                "  %{tmp} = insertvalue {{ {} }} {agg}, {all} {av}, {i}",
                                ts.iter()
                                    .map(|t| llvm_ty(
                                        &runtime_ty_from_surface(t),
                                        self.structs,
                                        self.enums
                                    ))
                                    .collect::<Vec<_>>()
                                    .join(", "),
                                agg = agg,
                                all = all,
                                av = av,
                                i = i
                            )
                            .unwrap();
                            agg = format!("%{tmp}");
                        }
                        let tmp = self.fresh();
                        writeln!(
                            self.out,
                            "  %{tmp} = insertvalue {cur}, {{ {} }} {agg}, {payload_idx}",
                            ts.iter()
                                .map(|t| llvm_ty(
                                    &runtime_ty_from_surface(t),
                                    self.structs,
                                    self.enums
                                ))
                                .collect::<Vec<_>>()
                                .join(", "),
                            cur = cur,
                            agg = agg,
                            payload_idx = payload_idx
                        )
                        .unwrap();
                        cur = format!("%{tmp}");
                    }
                    EnumVariantFields::Struct(fs) => {
                        let mut agg = "undef".to_string();
                        for (i, (arg, (_, sty))) in args.iter().zip(fs.iter()).enumerate() {
                            let (aty, av) =
                                self.emit_expr(arg, slots, Some(&runtime_ty_from_surface(sty)));
                            let all = llvm_ty(&aty, self.structs, self.enums);
                            let tmp = self.fresh();
                            let inner = fs
                                .iter()
                                .map(|(_, t)| llvm_ty(
                                    &runtime_ty_from_surface(t),
                                    self.structs,
                                    self.enums
                                ))
                                .collect::<Vec<_>>()
                                .join(", ");
                            writeln!(
                                self.out,
                                "  %{tmp} = insertvalue {{ {inner} }} {agg}, {all} {av}, {i}"
                            )
                            .unwrap();
                            agg = format!("%{tmp}");
                        }
                        let inner = fs
                            .iter()
                            .map(|(_, t)| llvm_ty(
                                &runtime_ty_from_surface(t),
                                self.structs,
                                self.enums
                            ))
                            .collect::<Vec<_>>()
                            .join(", ");
                        let tmp = self.fresh();
                        writeln!(
                            self.out,
                            "  %{tmp} = insertvalue {cur}, {{ {inner} }} {agg}, {payload_idx}"
                        )
                        .unwrap();
                        cur = format!("%{tmp}");
                    }
                }
                (RuntimeTy::Enum(name.clone()), cur)
            }
            ErasedExpr::ArrayLit(rt, elems) => self.emit_array_lit(rt, elems, slots),
            ErasedExpr::ArrayGet(rt, arr, idx) => self.emit_array_get(rt, arr, idx, slots),
            ErasedExpr::ArraySet(rt, arr, idx, val) => {
                self.emit_array_set(rt, arr, idx, val, slots);
                (RuntimeTy::Unit, "0".into())
            }
            ErasedExpr::AddrOf(rt, value) => self.emit_addr_of(rt, value, slots),
            ErasedExpr::Deref(rt, ptr) => self.emit_deref(rt, ptr, slots),
            ErasedExpr::Len(rt, arr) => self.emit_len(rt, arr, slots),
            ErasedExpr::HeapAlloc(rt, value) => self.emit_heap_alloc(rt, value, slots),
            ErasedExpr::HeapDealloc(rt, ptr) => {
                self.emit_heap_dealloc(rt, ptr, slots);
                (RuntimeTy::Unit, "0".into())
            }
            ErasedExpr::HeapRealloc(rt, ptr, value) => {
                self.emit_heap_realloc(rt, ptr, value, slots)
            }
            ErasedExpr::MatrixNew {
                elem,
                rows,
                cols,
                outer_rt,
                src,
            } => self.emit_matrix_new(elem, *rows, *cols, outer_rt, src, slots),
            ErasedExpr::MatrixToArray {
                elem,
                rows,
                cols,
                outer_rt,
                matrix,
            } => self.emit_matrix_to_array(elem, *rows, *cols, outer_rt, matrix, slots),
            ErasedExpr::MatrixDrop(rt, matrix) => {
                self.emit_matrix_drop(rt, matrix, slots);
                (RuntimeTy::Unit, "0".into())
            }
            ErasedExpr::While(cond, body) => {
                self.emit_while(cond, body, slots);
                (RuntimeTy::Unit, "0".into())
            }
            ErasedExpr::Loop(body) => {
                self.emit_loop(body, slots);
                (RuntimeTy::Unit, "0".into())
            }
            ErasedExpr::For { var, start, end, body } => {
                self.emit_for(var, start, end, body, slots);
                (RuntimeTy::Unit, "0".into())
            }
            ErasedExpr::Break => {
                let exit = self
                    .loop_exit_stack
                    .last()
                    .expect("break outside loop")
                    .clone();
                writeln!(self.out, "  br label %{exit}").unwrap();
                self.terminated = true;
                (RuntimeTy::Unit, "0".into())
            }
            ErasedExpr::Assign(target, value) => {
                self.emit_assign(target, value, slots);
                (RuntimeTy::Unit, "0".into())
            }
            ErasedExpr::Match {
                enum_name,
                scrutinee,
                arms,
            } => {
                let (ety, ev) = self.emit_expr(scrutinee, slots, None);
                assert!(matches!(ety, RuntimeTy::Enum(_)));
                let edef_idx = self
                    .enums
                    .iter()
                    .position(|e| e.name == *enum_name)
                    .expect("enum decl");
                let llvm_en = format!("%enum.{}", sanitize(enum_name));
                let tag = self.fresh();
                writeln!(self.out, "  %{tag} = extractvalue {llvm_en} {ev}, 0").unwrap();
                let ret_ty = expected.cloned().expect("match needs expected type");
                let edef = &self.enums[edef_idx];
                self.emit_match(
                    enum_name,
                    edef,
                    ev,
                    &tag,
                    arms,
                    slots,
                    &ret_ty,
                )
            }
            ErasedExpr::Quant { .. } => {
                panic!("quantum operations require the QIR backend (`-q`)")
            }
        }
    }

    fn emit_match(
        &mut self,
        enum_name: &str,
        edef: &EnumDef,
        scrut_val: String,
        tag_reg: &str,
        arms: &[ErasedArm],
        slots: &mut Vec<(RuntimeTy, String)>,
        ret_ty: &RuntimeTy,
    ) -> (RuntimeTy, String) {
        let llvm_en = format!("%enum.{}", sanitize(enum_name));
        let default_lbl = self.fresh_label("match.default");
        let merge_lbl = self.fresh_label("match.merge");
        let ret_ll = llvm_ty(ret_ty, self.structs, self.enums);
        let dst = self.fresh();
        let arm_lbls: Vec<String> = arms
            .iter()
            .map(|_| self.fresh_label("match.arm"))
            .collect();

        write!(
            self.out,
            "  switch i32 %{tag_reg}, label %{default_lbl} ["
        )
        .unwrap();
        for (arm, lbl) in arms.iter().zip(&arm_lbls) {
            write!(self.out, " i32 {}, label %{lbl}", arm.variant).unwrap();
        }
        writeln!(self.out, " ]").unwrap();
        writeln!(self.out, "{default_lbl}:").unwrap();
        writeln!(self.out, "  unreachable").unwrap();

        let mut phi_ins = Vec::new();
        for (arm, lbl) in arms.iter().zip(&arm_lbls) {
            writeln!(self.out, "{lbl}:").unwrap();
            let payload_idx = arm.variant as usize + 1;
            let vdef = &edef.variants[arm.variant as usize];
            let binding_tys = variant_binding_tys(vdef);
            let mut arm_slots: Vec<(RuntimeTy, String)> = Vec::new();
            for (i, bty) in binding_tys.iter().enumerate() {
                let bptr = format!("%match.{}", self.fresh());
                let bll = llvm_ty(bty, self.structs, self.enums);
                let bval = self.fresh();
                match &vdef.fields {
                    EnumVariantFields::Tuple(ts) if ts.len() == 1 => {
                        writeln!(
                            self.out,
                            "  %{bval} = extractvalue {llvm_en} {scrut_val}, {payload_idx}"
                        )
                        .unwrap();
                    }
                    EnumVariantFields::Tuple(_) | EnumVariantFields::Struct(_) => {
                        let pl = self.fresh();
                        writeln!(
                            self.out,
                            "  %{pl} = extractvalue {llvm_en} {scrut_val}, {payload_idx}"
                        )
                        .unwrap();
                        writeln!(
                            self.out,
                            "  %{bval} = extractvalue {} %{pl}, {i}",
                            payload_type_llvm(vdef, self.structs, self.enums)
                        )
                        .unwrap();
                    }
                    EnumVariantFields::Unit => break,
                }
                writeln!(self.out, "  {bptr} = alloca {bll}").unwrap();
                writeln!(self.out, "  store {bll} %{bval}, ptr {bptr}").unwrap();
                arm_slots.push((bty.clone(), bptr));
            }
            let (_, bv) = self.emit_expr(&arm.body, &mut arm_slots, Some(ret_ty));
            phi_ins.push((bv, lbl.clone()));
            writeln!(self.out, "  br label %{merge_lbl}").unwrap();
        }

        writeln!(self.out, "{merge_lbl}:").unwrap();
        write!(self.out, "  %{dst} = phi {ret_ll} ").unwrap();
        for (i, (val, lbl)) in phi_ins.iter().enumerate() {
            if i > 0 {
                write!(self.out, ", ").unwrap();
            }
            write!(self.out, "[{val}, %{lbl}]").unwrap();
        }
        writeln!(self.out).unwrap();
        (ret_ty.clone(), format!("%{dst}"))
    }

    fn array_ll(rt: &RuntimeTy, structs: &[StructDef], enums: &[EnumDef]) -> String {
        match rt {
            RuntimeTy::Array { elem, len } => {
                format!("[{} x {}]", len, llvm_ty(elem, structs, enums))
            }
            _ => panic!("expected array runtime type"),
        }
    }

    fn array_elem_rt(rt: &RuntimeTy) -> RuntimeTy {
        match rt {
            RuntimeTy::Array { elem, .. } => *elem.clone(),
            _ => panic!("expected array runtime type"),
        }
    }

    fn ptr_pointee_rt(rt: &RuntimeTy) -> RuntimeTy {
        match rt {
            RuntimeTy::Ptr(inner) => *inner.clone(),
            _ => panic!("expected pointer runtime type"),
        }
    }

    fn emit_array_lit(
        &mut self,
        rt: &RuntimeTy,
        elems: &[ErasedExpr],
        slots: &mut Vec<(RuntimeTy, String)>,
    ) -> (RuntimeTy, String) {
        let arr_ll = Self::array_ll(rt, self.structs, self.enums);
        let ptr = self.fresh();
        writeln!(self.out, "  %{ptr} = alloca {arr_ll}").unwrap();
        let elem_rt = Self::array_elem_rt(rt);
        for (i, elem) in elems.iter().enumerate() {
            let (ety, ev) = self.emit_expr(elem, slots, Some(&elem_rt));
            let ell = llvm_ty(&ety, self.structs, self.enums);
            let gep = self.fresh();
            writeln!(
                self.out,
                "  %{gep} = getelementptr inbounds {arr_ll}, ptr %{ptr}, i64 0, i64 {i}"
            )
            .unwrap();
            writeln!(self.out, "  store {ell} {ev}, ptr %{gep}").unwrap();
        }
        let dst = self.fresh();
        writeln!(self.out, "  %{dst} = load {arr_ll}, ptr %{ptr}").unwrap();
        (rt.clone(), format!("%{dst}"))
    }

    fn materialize_array_ptr(
        &mut self,
        rt: &RuntimeTy,
        arr_val: &str,
    ) -> String {
        let arr_ll = Self::array_ll(rt, self.structs, self.enums);
        let ptr = self.fresh();
        writeln!(self.out, "  %{ptr} = alloca {arr_ll}").unwrap();
        writeln!(self.out, "  store {arr_ll} {arr_val}, ptr %{ptr}").unwrap();
        format!("%{ptr}")
    }

    fn array_slot_ptr(
        &self,
        rt: &RuntimeTy,
        arr: &ErasedExpr,
        slots: &[(RuntimeTy, String)],
    ) -> Option<String> {
        if let ErasedExpr::Var(level) = arr {
            let (_, ptr) = &slots[*level as usize];
            return Some(ptr.clone());
        }
        None
    }

    fn emit_array_get(
        &mut self,
        rt: &RuntimeTy,
        arr: &ErasedExpr,
        idx: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) -> (RuntimeTy, String) {
        let (_, iv) = self.emit_expr(idx, slots, Some(&RuntimeTy::I32));
        let arr_ll = Self::array_ll(rt, self.structs, self.enums);
        let aptr = if let Some(ptr) = self.array_slot_ptr(rt, arr, slots) {
            ptr
        } else {
            let (_, av) = self.emit_expr(arr, slots, Some(rt));
            self.materialize_array_ptr(rt, &av)
        };
        let idx64 = self.fresh();
        writeln!(self.out, "  %{idx64} = sext i32 {iv} to i64").unwrap();
        let gep = self.fresh();
        writeln!(
            self.out,
            "  %{gep} = getelementptr inbounds {arr_ll}, ptr {aptr}, i64 0, i64 %{idx64}"
        )
        .unwrap();
        let elem_rt = Self::array_elem_rt(rt);
        let ell = llvm_ty(&elem_rt, self.structs, self.enums);
        let dst = self.fresh();
        writeln!(self.out, "  %{dst} = load {ell}, ptr %{gep}").unwrap();
        (elem_rt, format!("%{dst}"))
    }

    fn emit_array_set(
        &mut self,
        rt: &RuntimeTy,
        arr: &ErasedExpr,
        idx: &ErasedExpr,
        val: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) {
        let (_, iv) = self.emit_expr(idx, slots, Some(&RuntimeTy::I32));
        let elem_rt = Self::array_elem_rt(rt);
        let (_, vv) = self.emit_expr(val, slots, Some(&elem_rt));
        let arr_ll = Self::array_ll(rt, self.structs, self.enums);
        let aptr = if let Some(ptr) = self.array_slot_ptr(rt, arr, slots) {
            ptr
        } else {
            let (_, av) = self.emit_expr(arr, slots, Some(rt));
            self.materialize_array_ptr(rt, &av)
        };
        let idx64 = self.fresh();
        writeln!(self.out, "  %{idx64} = sext i32 {iv} to i64").unwrap();
        let gep = self.fresh();
        writeln!(
            self.out,
            "  %{gep} = getelementptr inbounds {arr_ll}, ptr {aptr}, i64 0, i64 %{idx64}"
        )
        .unwrap();
        let ell = llvm_ty(&elem_rt, self.structs, self.enums);
        writeln!(self.out, "  store {ell} {vv}, ptr %{gep}").unwrap();
    }

    fn emit_addr_of(
        &mut self,
        rt: &RuntimeTy,
        value: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) -> (RuntimeTy, String) {
        if let ErasedExpr::Var(level) = value {
            let (_, ptr) = &slots[*level as usize];
            return (rt.clone(), ptr.clone());
        }
        let pointee = Self::ptr_pointee_rt(rt);
        let (ty, val) = self.emit_expr(value, slots, Some(&pointee));
        let ll = llvm_ty(&ty, self.structs, self.enums);
        let ptr = self.fresh();
        writeln!(self.out, "  %{ptr} = alloca {ll}").unwrap();
        writeln!(self.out, "  store {ll} {val}, ptr %{ptr}").unwrap();
        (rt.clone(), format!("%{ptr}"))
    }

    fn emit_deref(
        &mut self,
        rt: &RuntimeTy,
        ptr: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) -> (RuntimeTy, String) {
        let (_, pv) = self.emit_expr(ptr, slots, Some(rt));
        let pointee = Self::ptr_pointee_rt(rt);
        let ell = llvm_ty(&pointee, self.structs, self.enums);
        let dst = self.fresh();
        writeln!(self.out, "  %{dst} = load {ell}, ptr {pv}").unwrap();
        (pointee, format!("%{dst}"))
    }

    fn emit_len(
        &mut self,
        rt: &RuntimeTy,
        arr: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) -> (RuntimeTy, String) {
        let _ = self.emit_expr(arr, slots, Some(rt));
        let len = match rt {
            RuntimeTy::Array { len, .. } => *len,
            _ => panic!("len expects array"),
        };
        (RuntimeTy::I32, format!("{len}"))
    }

    fn emit_heap_alloc(
        &mut self,
        rt: &RuntimeTy,
        value: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) -> (RuntimeTy, String) {
        let pointee = Self::ptr_pointee_rt(rt);
        let (ty, val) = self.emit_expr(value, slots, Some(&pointee));
        let ll = llvm_ty(&ty, self.structs, self.enums);
        let size = self.type_size_bytes(&ty);
        let heap = self.fresh();
        writeln!(self.out, "  %{heap} = call ptr @malloc(i64 {size})").unwrap();
        writeln!(self.out, "  store {ll} {val}, ptr %{heap}").unwrap();
        (rt.clone(), format!("%{heap}"))
    }

    fn emit_heap_dealloc(
        &mut self,
        rt: &RuntimeTy,
        ptr: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) {
        let (_, pv) = self.emit_expr(ptr, slots, Some(rt));
        writeln!(self.out, "  call void @free(ptr {pv})").unwrap();
    }

    fn emit_heap_realloc(
        &mut self,
        rt: &RuntimeTy,
        ptr: &ErasedExpr,
        value: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) -> (RuntimeTy, String) {
        let (_, old_ptr) = self.emit_expr(ptr, slots, Some(rt));
        let pointee = Self::ptr_pointee_rt(rt);
        let (ty, val) = self.emit_expr(value, slots, Some(&pointee));
        let ll = llvm_ty(&ty, self.structs, self.enums);
        let size = self.type_size_bytes(&ty);
        let new_ptr = self.fresh();
        writeln!(
            self.out,
            "  %{new_ptr} = call ptr @realloc(ptr {old_ptr}, i64 {size})"
        )
        .unwrap();
        writeln!(self.out, "  store {ll} {val}, ptr %{new_ptr}").unwrap();
        (rt.clone(), format!("%{new_ptr}"))
    }

    fn type_size_bytes(&self, ty: &RuntimeTy) -> i64 {
        match ty {
            RuntimeTy::I8 | RuntimeTy::U8 | RuntimeTy::Bool => 1,
            RuntimeTy::I16 | RuntimeTy::U16 => 2,
            RuntimeTy::I32 => 4,
            RuntimeTy::I64 | RuntimeTy::U64 => 8,
            RuntimeTy::I128 | RuntimeTy::U128 => 16,
            RuntimeTy::Struct(name) => {
                let sdef = self
                    .structs
                    .iter()
                    .find(|s| s.name == *name)
                    .expect("struct decl");
                sdef.fields.iter().map(|(_, t)| {
                    self.type_size_bytes(&runtime_ty_from_surface(t))
                }).sum()
            }
            RuntimeTy::Enum(name) => {
                let _ = self
                    .enums
                    .iter()
                    .find(|e| e.name == *name)
                    .expect("enum decl");
                16
            }
            RuntimeTy::Array { elem, len } => {
                self.type_size_bytes(elem) * (*len as i64)
            }
            RuntimeTy::Ptr(_) | RuntimeTy::Matrix { .. } => 8,
            RuntimeTy::F16 => 2,
            RuntimeTy::F32 => 4,
            RuntimeTy::F64 => 8,
            RuntimeTy::String => 8,
            RuntimeTy::Unit => 4,
            RuntimeTy::Qubit | RuntimeTy::Result => {
                panic!("quantum types require the QIR backend (`-q`)")
            }
        }
    }

    fn matrix_field_ptr(&mut self, matrix: &str, field: u32) -> String {
        let out = self.fresh();
        writeln!(
            self.out,
            "  %{out} = getelementptr inbounds {{ i64, ptr, i64, i64 }}, ptr {matrix}, i32 0, i32 {field}"
        )
        .unwrap();
        format!("%{out}")
    }

    fn matrix_load_i64_field(&mut self, matrix: &str, field: u32) -> String {
        let ptr = self.matrix_field_ptr(matrix, field);
        let out = self.fresh();
        writeln!(self.out, "  %{out} = load i64, ptr {ptr}").unwrap();
        format!("%{out}")
    }

    fn matrix_load_data_ptr(&mut self, matrix: &str) -> String {
        let ptr = self.matrix_field_ptr(matrix, 1);
        let out = self.fresh();
        writeln!(self.out, "  %{out} = load ptr, ptr {ptr}").unwrap();
        format!("%{out}")
    }

    fn emit_matrix_new(
        &mut self,
        elem_rt: &RuntimeTy,
        rows: u32,
        cols: u32,
        outer_rt: &RuntimeTy,
        src: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) -> (RuntimeTy, String) {
        let matrix_rt = RuntimeTy::Matrix {
            elem: Box::new(elem_rt.clone()),
        };
        let (_, src_val) = self.emit_expr(src, slots, Some(outer_rt));
        let len = rows as i64 * cols as i64;
        let bytes = len * self.type_size_bytes(elem_rt);
        let data = self.fresh();
        let matrix = self.fresh();
        writeln!(self.out, "  %{data} = call ptr @malloc(i64 {bytes})").unwrap();
        writeln!(self.out, "  %{matrix} = call ptr @malloc(i64 32)").unwrap();

        let rc_ptr = self.matrix_field_ptr(&format!("%{matrix}"), 0);
        let data_ptr = self.matrix_field_ptr(&format!("%{matrix}"), 1);
        let rows_ptr = self.matrix_field_ptr(&format!("%{matrix}"), 2);
        let cols_ptr = self.matrix_field_ptr(&format!("%{matrix}"), 3);
        writeln!(self.out, "  store i64 1, ptr {rc_ptr}").unwrap();
        writeln!(self.out, "  store ptr %{data}, ptr {data_ptr}").unwrap();
        writeln!(self.out, "  store i64 {rows}, ptr {rows_ptr}").unwrap();
        writeln!(self.out, "  store i64 {cols}, ptr {cols_ptr}").unwrap();

        let RuntimeTy::Array {
            elem: row_rt,
            len: row_len,
        } = outer_rt
        else {
            panic!("matrix source must be nested array");
        };
        let RuntimeTy::Array {
            elem: cell_rt,
            len: col_len,
        } = row_rt.as_ref()
        else {
            panic!("matrix source rows must be arrays");
        };
        assert_eq!(*row_len, rows);
        assert_eq!(*col_len, cols);

        let src_ll = Self::array_ll(outer_rt, self.structs, self.enums);
        let row_ll = Self::array_ll(row_rt, self.structs, self.enums);
        for row in 0..rows {
            let row_val = self.fresh();
            writeln!(
                self.out,
                "  %{row_val} = extractvalue {src_ll} {src_val}, {row}"
            )
            .unwrap();
            for col in 0..cols {
                let raw_cell = self.fresh();
                let flat = row as i64 * cols as i64 + col as i64;
                let cell_ptr = self.fresh();
                writeln!(
                    self.out,
                    "  %{raw_cell} = extractvalue {row_ll} %{row_val}, {col}"
                )
                .unwrap();
                writeln!(
                    self.out,
                    "  %{cell_ptr} = getelementptr inbounds {}, ptr %{data}, i64 {flat}",
                    llvm_ty(cell_rt, self.structs, self.enums)
                )
                .unwrap();
                writeln!(
                    self.out,
                    "  store {} %{raw_cell}, ptr %{cell_ptr}",
                    llvm_ty(cell_rt, self.structs, self.enums)
                )
                .unwrap();
            }
        }

        (matrix_rt, format!("%{matrix}"))
    }

    fn emit_matrix_to_array(
        &mut self,
        elem_rt: &RuntimeTy,
        rows: u32,
        cols: u32,
        outer_rt: &RuntimeTy,
        matrix: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) -> (RuntimeTy, String) {
        let matrix_rt = RuntimeTy::Matrix {
            elem: Box::new(elem_rt.clone()),
        };
        let (_, matrix_val) = self.emit_expr(matrix, slots, Some(&matrix_rt));
        let data = self.matrix_load_data_ptr(&matrix_val);
        let RuntimeTy::Array {
            elem: row_rt,
            len: row_len,
        } = outer_rt
        else {
            panic!("matrix target must be nested array");
        };
        assert_eq!(*row_len, rows);
        let row_ll = Self::array_ll(row_rt, self.structs, self.enums);
        let arr_ll = Self::array_ll(outer_rt, self.structs, self.enums);
        let mut arr_agg = "poison".to_string();

        for row in 0..rows {
            let mut row_agg = "poison".to_string();
            for col in 0..cols {
                let flat = row as i64 * cols as i64 + col as i64;
                let cell_ptr = self.fresh();
                let cell = self.fresh();
                writeln!(
                    self.out,
                    "  %{cell_ptr} = getelementptr inbounds {}, ptr {data}, i64 {flat}",
                    llvm_ty(elem_rt, self.structs, self.enums)
                )
                .unwrap();
                writeln!(
                    self.out,
                    "  %{cell} = load {}, ptr %{cell_ptr}",
                    llvm_ty(elem_rt, self.structs, self.enums)
                )
                .unwrap();
                let next_row = self.fresh();
                writeln!(
                    self.out,
                    "  %{next_row} = insertvalue {row_ll} {row_agg}, {} %{cell}, {col}",
                    llvm_ty(elem_rt, self.structs, self.enums)
                )
                .unwrap();
                row_agg = format!("%{next_row}");
            }
            let next_arr = self.fresh();
            writeln!(
                self.out,
                "  %{next_arr} = insertvalue {arr_ll} {arr_agg}, {row_ll} {row_agg}, {row}"
            )
            .unwrap();
            arr_agg = format!("%{next_arr}");
        }

        (outer_rt.clone(), arr_agg)
    }

    fn emit_matrix_drop(
        &mut self,
        rt: &RuntimeTy,
        matrix: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) {
        let (_, matrix_val) = self.emit_expr(matrix, slots, Some(rt));
        let rc_ptr = self.matrix_field_ptr(&matrix_val, 0);
        let old = self.fresh();
        let new = self.fresh();
        let is_zero = self.fresh();
        let free_lbl = self.fresh_label("matrix.drop.free");
        let cont_lbl = self.fresh_label("matrix.drop.cont");
        writeln!(self.out, "  %{old} = load i64, ptr {rc_ptr}").unwrap();
        writeln!(self.out, "  %{new} = sub i64 %{old}, 1").unwrap();
        writeln!(self.out, "  store i64 %{new}, ptr {rc_ptr}").unwrap();
        writeln!(self.out, "  %{is_zero} = icmp eq i64 %{new}, 0").unwrap();
        writeln!(
            self.out,
            "  br i1 %{is_zero}, label %{free_lbl}, label %{cont_lbl}"
        )
        .unwrap();
        writeln!(self.out, "{free_lbl}:").unwrap();
        let data = self.matrix_load_data_ptr(&matrix_val);
        writeln!(self.out, "  call void @free(ptr {data})").unwrap();
        writeln!(self.out, "  call void @free(ptr {matrix_val})").unwrap();
        writeln!(self.out, "  br label %{cont_lbl}").unwrap();
        writeln!(self.out, "{cont_lbl}:").unwrap();
    }

    fn emit_assign(
        &mut self,
        target: &ErasedExpr,
        value: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) {
        if let ErasedExpr::Var(level) = target {
            let (ty, ptr) = slots[*level as usize].clone();
            let (_, vv) = self.emit_expr(value, slots, Some(&ty));
            let ll = llvm_ty(&ty, self.structs, self.enums);
            writeln!(self.out, "  store {ll} {vv}, ptr {ptr}").unwrap();
            return;
        }
        if let ErasedExpr::Deref(rt, ptr) = target {
            let (_, pv) = self.emit_expr(ptr, slots, Some(rt));
            let pointee = Self::ptr_pointee_rt(rt);
            let (_, vv) = self.emit_expr(value, slots, Some(&pointee));
            let ell = llvm_ty(&pointee, self.structs, self.enums);
            writeln!(self.out, "  store {ell} {vv}, ptr {pv}").unwrap();
            return;
        }
        let (tty, _) = self.emit_expr(target, slots, None);
        let (_, vv) = self.emit_expr(value, slots, Some(&tty));
        let _ = vv;
    }

    fn emit_while(
        &mut self,
        cond: &ErasedExpr,
        body: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) {
        let cond_lbl = self.fresh_label("while.cond");
        let body_lbl = self.fresh_label("while.body");
        let exit_lbl = self.fresh_label("while.exit");
        writeln!(self.out, "  br label %{cond_lbl}").unwrap();
        writeln!(self.out, "{cond_lbl}:").unwrap();
        let (_, cv) = self.emit_expr(cond, slots, Some(&RuntimeTy::Bool));
        writeln!(
            self.out,
            "  br i1 {cv}, label %{body_lbl}, label %{exit_lbl}"
        )
        .unwrap();
        writeln!(self.out, "{body_lbl}:").unwrap();
        self.loop_exit_stack.push(exit_lbl.clone());
        self.terminated = false;
        let _ = self.emit_expr(body, slots, Some(&RuntimeTy::Unit));
        self.loop_exit_stack.pop();
        if !self.terminated {
            writeln!(self.out, "  br label %{cond_lbl}").unwrap();
        }
        self.terminated = false;
        writeln!(self.out, "{exit_lbl}:").unwrap();
    }

    fn emit_loop(&mut self, body: &ErasedExpr, slots: &mut Vec<(RuntimeTy, String)>) {
        let iter_lbl = self.fresh_label("loop.iter");
        let exit_lbl = self.fresh_label("loop.exit");
        writeln!(self.out, "  br label %{iter_lbl}").unwrap();
        writeln!(self.out, "{iter_lbl}:").unwrap();
        self.loop_exit_stack.push(exit_lbl.clone());
        self.terminated = false;
        let _ = self.emit_expr(body, slots, Some(&RuntimeTy::Unit));
        self.loop_exit_stack.pop();
        if !self.terminated {
            writeln!(self.out, "  br label %{iter_lbl}").unwrap();
        }
        self.terminated = false;
        writeln!(self.out, "{exit_lbl}:").unwrap();
    }

    fn emit_for(
        &mut self,
        var: &str,
        start: &ErasedExpr,
        end: &ErasedExpr,
        body: &ErasedExpr,
        slots: &mut Vec<(RuntimeTy, String)>,
    ) {
        let header = self.fresh_label("for.header");
        let body_lbl = self.fresh_label("for.body");
        let latch = self.fresh_label("for.latch");
        let exit = self.fresh_label("for.exit");
        let (_, v_start) = self.emit_expr(start, slots, Some(&RuntimeTy::I32));
        let (_, v_end) = self.emit_expr(end, slots, Some(&RuntimeTy::I32));
        let var_ptr = format!("%{}.{}", sanitize(var), self.fresh());
        writeln!(self.out, "  {var_ptr} = alloca i32").unwrap();
        writeln!(self.out, "  store i32 {v_start}, ptr {var_ptr}").unwrap();
        writeln!(self.out, "  br label %{header}").unwrap();
        writeln!(self.out, "{header}:").unwrap();
        let iv = self.fresh();
        writeln!(self.out, "  %{iv} = load i32, ptr {var_ptr}").unwrap();
        let cmp = self.fresh();
        writeln!(self.out, "  %{cmp} = icmp slt i32 %{iv}, {v_end}").unwrap();
        writeln!(
            self.out,
            "  br i1 %{cmp}, label %{body_lbl}, label %{exit}"
        )
        .unwrap();
        writeln!(self.out, "{body_lbl}:").unwrap();
        let mut body_slots = slots.clone();
        body_slots.push((RuntimeTy::I32, var_ptr.clone()));
        self.loop_exit_stack.push(exit.clone());
        self.terminated = false;
        let _ = self.emit_expr(body, &mut body_slots, Some(&RuntimeTy::Unit));
        self.loop_exit_stack.pop();
        writeln!(self.out, "  br label %{latch}").unwrap();
        writeln!(self.out, "{latch}:").unwrap();
        let next = self.fresh();
        writeln!(self.out, "  %{next} = add nsw i32 %{iv}, 1").unwrap();
        writeln!(self.out, "  store i32 %{next}, ptr {var_ptr}").unwrap();
        writeln!(self.out, "  br label %{header}").unwrap();
        self.terminated = false;
        writeln!(self.out, "{exit}:").unwrap();
    }

    fn load_slot(&mut self, slots: &[(RuntimeTy, String)], level: u32) -> (RuntimeTy, String) {
        let (ty, ptr) = &slots[level as usize];
        let ll = llvm_ty(ty, self.structs, self.enums);
        let dst = self.fresh();
        writeln!(self.out, "  %{dst} = load {ll}, ptr {ptr}").unwrap();
        (ty.clone(), format!("%{dst}"))
    }

    fn emit_println(&mut self, ty: &RuntimeTy, value: &str, newline: bool) {
        match ty {
            RuntimeTy::I32 => {
                let fmt = if newline {
                    "@nialang.std.fmt.i32"
                } else {
                    "@nialang.std.fmt.i32.nn"
                };
                writeln!(self.out, "  call i32 (ptr, ...) @printf(ptr {fmt}, i32 {value})").unwrap();
            }
            RuntimeTy::I8 => {
                let ext = self.fresh();
                writeln!(self.out, "  %{ext} = sext i8 {value} to i32").unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr @nialang.std.fmt.i32, i32 %{ext})"
                )
                .unwrap();
            }
            RuntimeTy::U8 => {
                let ext = self.fresh();
                writeln!(self.out, "  %{ext} = zext i8 {value} to i32").unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr @nialang.std.fmt.u32, i32 %{ext})"
                )
                .unwrap();
            }
            RuntimeTy::U16 => {
                let ext = self.fresh();
                writeln!(self.out, "  %{ext} = zext i16 {value} to i32").unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr @nialang.std.fmt.u32, i32 %{ext})"
                )
                .unwrap();
            }
            RuntimeTy::I64 => {
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr @nialang.std.fmt.i64, i64 {value})"
                )
                .unwrap();
            }
            RuntimeTy::U128 | RuntimeTy::I128 => {
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr @nialang.std.fmt.i128hex, i64 0, i64 {value})"
                )
                .unwrap();
            }
            RuntimeTy::Bool => {
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr @nialang.std.fmt.i32, i32 {value})"
                )
                .unwrap();
            }
            RuntimeTy::F16 | RuntimeTy::F32 | RuntimeTy::F64 => {
                let (sym, sz) = if newline {
                    ("@nialang.std.fmt.f64", 4)
                } else {
                    ("@nialang.std.fmt.f64.nn", 3)
                };
                match ty {
                    RuntimeTy::F64 => {
                        writeln!(
                            self.out,
                            "  call i32 (ptr, ...) @printf(ptr {sym}, double {value})"
                        )
                        .unwrap();
                    }
                    RuntimeTy::F32 => {
                        let e = self.fresh();
                        writeln!(self.out, "  %{e} = fpext float {value} to double").unwrap();
                        writeln!(
                            self.out,
                            "  call i32 (ptr, ...) @printf(ptr {sym}, double %{e})"
                        )
                        .unwrap();
                    }
                    RuntimeTy::F16 => {
                        let e = self.fresh();
                        writeln!(self.out, "  %{e} = fpext half {value} to double").unwrap();
                        writeln!(
                            self.out,
                            "  call i32 (ptr, ...) @printf(ptr {sym}, double %{e})"
                        )
                        .unwrap();
                    }
                    _ => {
                        let _ = sz;
                        unreachable!()
                    }
                }
            }
            RuntimeTy::String => {
                let sym = if newline {
                    "@nialang.std.fmt.str"
                } else {
                    "@nialang.std.fmt.str.nn"
                };
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {sym}, ptr {value})"
                )
                .unwrap();
            }
            RuntimeTy::Enum(name) => {
                self.emit_print_enum(name, value, newline);
            }
            RuntimeTy::Array { elem, len } => {
                self.emit_print_array(elem, *len, value, newline);
            }
            RuntimeTy::Struct(name) => {
                self.emit_print_struct(name, value, newline);
            }
            RuntimeTy::Ptr(_) => {
                let sym = if newline {
                    "@nialang.std.fmt.ptrhex"
                } else {
                    "@nialang.std.fmt.ptrhex.nn"
                };
                let addr = self.fresh();
                writeln!(self.out, "  %{addr} = ptrtoint ptr {value} to i64").unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {sym}, i64 %{addr})"
                )
                .unwrap();
            }
            RuntimeTy::Matrix { elem } => {
                self.emit_print_matrix(elem, value, newline);
            }
            other => panic!("println not supported for {other:?}"),
        }
    }

    fn emit_print_struct(&mut self, sname: &str, struct_v: &str, newline: bool) {
        let sdef = self
            .structs
            .iter()
            .find(|s| s.name == sname)
            .expect("struct decl");
        let llvm_st = format!("%struct.{}", sanitize(sname));
        if sdef.is_tuple {
            writeln!(
                self.out,
                "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.tuple_open, i32 2)"
            )
            .unwrap();
            for (i, (_, fty)) in sdef.fields.iter().enumerate() {
                if i > 0 {
                    writeln!(
                        self.out,
                        "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_sep, i32 3)"
                    )
                    .unwrap();
                }
                let fv = self.fresh();
                writeln!(
                    self.out,
                    "  %{fv} = extractvalue {llvm_st} {struct_v}, {i}"
                )
                .unwrap();
                self.emit_print_value(&runtime_ty_from_surface(fty), &format!("%{fv}"), false);
            }
            let close = if newline {
                "@nialang.std.txt.tuple_close_ln"
            } else {
                "@nialang.std.txt.tuple_close"
            };
            writeln!(
                self.out,
                "  call i32 (ptr, ...) @printf(ptr {close}, i32 {})",
                if newline { 3 } else { 2 }
            )
            .unwrap();
            return;
        }

        writeln!(
            self.out,
            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.obj_open, i32 2)"
        )
        .unwrap();
        for (i, (fname, fty)) in sdef.fields.iter().enumerate() {
            if i > 0 {
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_sep, i32 3)"
                )
                .unwrap();
            }
            let key_sym = struct_field_key_symbol(sname, fname);
            let key_len = format!("\"{fname}\": ").len() + 1;
            writeln!(
                self.out,
                "  call i32 (ptr, ...) @printf(ptr @{key_sym}, i32 {key_len})"
            )
            .unwrap();
            let fv = self.fresh();
            writeln!(
                self.out,
                "  %{fv} = extractvalue {llvm_st} {struct_v}, {i}"
            )
            .unwrap();
            self.emit_print_value(&runtime_ty_from_surface(fty), &format!("%{fv}"), false);
        }
        let close = if newline {
            "@nialang.std.txt.obj_close_ln"
        } else {
            "@nialang.std.txt.obj_close"
        };
        writeln!(
            self.out,
            "  call i32 (ptr, ...) @printf(ptr {close}, i32 {})",
            if newline { 3 } else { 2 }
        )
        .unwrap();
    }

    fn emit_print_matrix(&mut self, elem: &RuntimeTy, matrix: &str, newline: bool) {
        let rows = self.matrix_load_i64_field(matrix, 2);
        let cols = self.matrix_load_i64_field(matrix, 3);
        let data = self.matrix_load_data_ptr(matrix);
        let row_addr = self.fresh();
        let col_addr = self.fresh();
        writeln!(self.out, "  %{row_addr} = alloca i64").unwrap();
        writeln!(self.out, "  %{col_addr} = alloca i64").unwrap();
        writeln!(self.out, "  store i64 0, ptr %{row_addr}").unwrap();

        let row_cond = self.fresh_label("println.matrix.row.cond");
        let row_body = self.fresh_label("println.matrix.row.body");
        let row_sep = self.fresh_label("println.matrix.row.sep");
        let row_item = self.fresh_label("println.matrix.row.item");
        let row_latch = self.fresh_label("println.matrix.row.latch");
        let row_done = self.fresh_label("println.matrix.row.done");
        let col_cond = self.fresh_label("println.matrix.col.cond");
        let col_body = self.fresh_label("println.matrix.col.body");
        let col_sep = self.fresh_label("println.matrix.col.sep");
        let col_item = self.fresh_label("println.matrix.col.item");
        let col_latch = self.fresh_label("println.matrix.col.latch");
        let col_done = self.fresh_label("println.matrix.col.done");

        writeln!(
            self.out,
            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_open)"
        )
        .unwrap();
        writeln!(self.out, "  br label %{row_cond}").unwrap();

        writeln!(self.out, "{row_cond}:").unwrap();
        let row = self.fresh();
        let has_row = self.fresh();
        writeln!(self.out, "  %{row} = load i64, ptr %{row_addr}").unwrap();
        writeln!(self.out, "  %{has_row} = icmp slt i64 %{row}, {rows}").unwrap();
        writeln!(
            self.out,
            "  br i1 %{has_row}, label %{row_body}, label %{row_done}"
        )
        .unwrap();

        writeln!(self.out, "{row_body}:").unwrap();
        let first_row = self.fresh();
        writeln!(self.out, "  %{first_row} = icmp eq i64 %{row}, 0").unwrap();
        writeln!(
            self.out,
            "  br i1 %{first_row}, label %{row_item}, label %{row_sep}"
        )
        .unwrap();

        writeln!(self.out, "{row_sep}:").unwrap();
        writeln!(
            self.out,
            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_sep)"
        )
        .unwrap();
        writeln!(self.out, "  br label %{row_item}").unwrap();

        writeln!(self.out, "{row_item}:").unwrap();
        writeln!(
            self.out,
            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_open)"
        )
        .unwrap();
        writeln!(self.out, "  store i64 0, ptr %{col_addr}").unwrap();
        writeln!(self.out, "  br label %{col_cond}").unwrap();

        writeln!(self.out, "{col_cond}:").unwrap();
        let col = self.fresh();
        let has_col = self.fresh();
        writeln!(self.out, "  %{col} = load i64, ptr %{col_addr}").unwrap();
        writeln!(self.out, "  %{has_col} = icmp slt i64 %{col}, {cols}").unwrap();
        writeln!(
            self.out,
            "  br i1 %{has_col}, label %{col_body}, label %{col_done}"
        )
        .unwrap();

        writeln!(self.out, "{col_body}:").unwrap();
        let first_col = self.fresh();
        writeln!(self.out, "  %{first_col} = icmp eq i64 %{col}, 0").unwrap();
        writeln!(
            self.out,
            "  br i1 %{first_col}, label %{col_item}, label %{col_sep}"
        )
        .unwrap();

        writeln!(self.out, "{col_sep}:").unwrap();
        writeln!(
            self.out,
            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_sep)"
        )
        .unwrap();
        writeln!(self.out, "  br label %{col_item}").unwrap();

        writeln!(self.out, "{col_item}:").unwrap();
        let row_offset = self.fresh();
        let index = self.fresh();
        let cell_ptr = self.fresh();
        let cell = self.fresh();
        writeln!(self.out, "  %{row_offset} = mul i64 %{row}, {cols}").unwrap();
        writeln!(self.out, "  %{index} = add i64 %{row_offset}, %{col}").unwrap();
        writeln!(
            self.out,
            "  %{cell_ptr} = getelementptr inbounds {}, ptr {data}, i64 %{index}",
            llvm_ty(elem, self.structs, self.enums)
        )
        .unwrap();
        writeln!(
            self.out,
            "  %{cell} = load {}, ptr %{cell_ptr}",
            llvm_ty(elem, self.structs, self.enums)
        )
        .unwrap();
        self.emit_print_value(elem, &format!("%{cell}"), false);
        writeln!(self.out, "  br label %{col_latch}").unwrap();

        writeln!(self.out, "{col_latch}:").unwrap();
        let col_next = self.fresh();
        writeln!(self.out, "  %{col_next} = add i64 %{col}, 1").unwrap();
        writeln!(self.out, "  store i64 %{col_next}, ptr %{col_addr}").unwrap();
        writeln!(self.out, "  br label %{col_cond}").unwrap();

        writeln!(self.out, "{col_done}:").unwrap();
        writeln!(
            self.out,
            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_close)"
        )
        .unwrap();
        writeln!(self.out, "  br label %{row_latch}").unwrap();

        writeln!(self.out, "{row_latch}:").unwrap();
        let row_next = self.fresh();
        writeln!(self.out, "  %{row_next} = add i64 %{row}, 1").unwrap();
        writeln!(self.out, "  store i64 %{row_next}, ptr %{row_addr}").unwrap();
        writeln!(self.out, "  br label %{row_cond}").unwrap();

        writeln!(self.out, "{row_done}:").unwrap();
        let close = if newline {
            "@nialang.std.txt.arr_close_ln"
        } else {
            "@nialang.std.txt.arr_close"
        };
        writeln!(self.out, "  call i32 (ptr, ...) @printf(ptr {close})").unwrap();
    }

    fn emit_print_array(
        &mut self,
        elem: &RuntimeTy,
        len: u32,
        arr_val: &str,
        newline: bool,
    ) {
        let arr_rt = RuntimeTy::Array {
            elem: Box::new(elem.clone()),
            len,
        };
        let arr_ll = Self::array_ll(&arr_rt, self.structs, self.enums);
        let aptr = self.materialize_array_ptr(&arr_rt, arr_val);
        writeln!(
            self.out,
            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_open)"
        )
        .unwrap();
        let ell = llvm_ty(elem, self.structs, self.enums);
        for i in 0..len {
            let gep = self.fresh();
            writeln!(
                self.out,
                "  %{gep} = getelementptr inbounds {arr_ll}, ptr {aptr}, i64 0, i64 {i}"
            )
            .unwrap();
            let val = self.fresh();
            writeln!(self.out, "  %{val} = load {ell}, ptr %{gep}").unwrap();
            if i > 0 {
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_sep)"
                )
                .unwrap();
            }
            self.emit_print_value(elem, &format!("%{val}"), false);
        }
        let close = if newline {
            "@nialang.std.txt.arr_close_ln"
        } else {
            "@nialang.std.txt.arr_close"
        };
        writeln!(self.out, "  call i32 (ptr, ...) @printf(ptr {close})").unwrap();
    }

    fn emit_print_enum(&mut self, ename: &str, ev: &str, newline: bool) {
        let edef = self
            .enums
            .iter()
            .find(|e| e.name == ename)
            .expect("enum decl");
        let enum_ll = format!("%enum.{}", sanitize(ename));
        let tag = self.fresh();
        writeln!(self.out, "  %{tag} = extractvalue {enum_ll} {ev}, 0").unwrap();
        let default_lbl = self.fresh_label("println.enum.default");
        let cont_lbl = self.fresh_label("println.enum.cont");
        let arm_lbls: Vec<String> = edef
            .variants
            .iter()
            .map(|_| self.fresh_label("println.enum.arm"))
            .collect();
        write!(self.out, "  switch i32 %{tag}, label %{default_lbl} [").unwrap();
        for (i, lbl) in arm_lbls.iter().enumerate() {
            write!(self.out, " i32 {i}, label %{lbl}").unwrap();
        }
        writeln!(self.out, " ]").unwrap();
        writeln!(self.out, "{default_lbl}:").unwrap();
        writeln!(self.out, "  unreachable").unwrap();

        for (i, (vdef, lbl)) in edef.variants.iter().zip(&arm_lbls).enumerate() {
            writeln!(self.out, "{lbl}:").unwrap();
            let sym = enum_variant_prefix_symbol(ename, &vdef.name);
            let prefix_len = format!("{}: ", vdef.name).len() + 1;
            writeln!(
                self.out,
                "  call i32 (ptr, ...) @printf(ptr @{sym}, i32 {prefix_len})"
            )
            .unwrap();
            let payload_idx = i + 1;
            match &vdef.fields {
                EnumVariantFields::Unit => {
                    writeln!(
                        self.out,
                        "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.tuple_open, i32 2)"
                    )
                    .unwrap();
                    if newline {
                        writeln!(
                            self.out,
                            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.tuple_close_ln, i32 3)"
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            self.out,
                            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.tuple_close, i32 2)"
                        )
                        .unwrap();
                    }
                }
                EnumVariantFields::Tuple(ts) if ts.len() == 1 => {
                    let pl = self.fresh();
                    writeln!(
                        self.out,
                        "  %{pl} = extractvalue {enum_ll} {ev}, {payload_idx}"
                    )
                    .unwrap();
                    self.emit_print_value(
                        &runtime_ty_from_surface(&ts[0]),
                        &format!("%{pl}"),
                        newline,
                    );
                }
                EnumVariantFields::Tuple(ts) => {
                    let pl = self.fresh();
                    writeln!(
                        self.out,
                        "  %{pl} = extractvalue {enum_ll} {ev}, {payload_idx}"
                    )
                    .unwrap();
                    writeln!(
                        self.out,
                        "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.tuple_open, i32 2)"
                    )
                    .unwrap();
                    for (j, sty) in ts.iter().enumerate() {
                        if j > 0 {
                            writeln!(
                                self.out,
                                "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_sep, i32 3)"
                            )
                            .unwrap();
                        }
                        let fv = self.fresh();
                        writeln!(
                            self.out,
                            "  %{fv} = extractvalue {} %{pl}, {j}",
                            payload_type_llvm(vdef, self.structs, self.enums)
                        )
                        .unwrap();
                        self.emit_print_value(
                            &runtime_ty_from_surface(sty),
                            &format!("%{fv}"),
                            false,
                        );
                    }
                    if newline {
                        writeln!(
                            self.out,
                            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.tuple_close_ln, i32 3)"
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            self.out,
                            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.tuple_close, i32 2)"
                        )
                        .unwrap();
                    }
                }
                EnumVariantFields::Struct(fs) => {
                    let pl = self.fresh();
                    writeln!(
                        self.out,
                        "  %{pl} = extractvalue {enum_ll} {ev}, {payload_idx}"
                    )
                    .unwrap();
                    writeln!(
                        self.out,
                        "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.obj_open, i32 2)"
                    )
                    .unwrap();
                    for (j, (fname, sty)) in fs.iter().enumerate() {
                        if j > 0 {
                            writeln!(
                                self.out,
                                "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.arr_sep, i32 3)"
                            )
                            .unwrap();
                        }
                        let key_sym = enum_struct_field_key_symbol(ename, &vdef.name, fname);
                        let key_len = format!("\"{fname}\": ").len() + 1;
                        writeln!(
                            self.out,
                            "  call i32 (ptr, ...) @printf(ptr @{key_sym}, i32 {key_len})"
                        )
                        .unwrap();
                        let fv = self.fresh();
                        writeln!(
                            self.out,
                            "  %{fv} = extractvalue {} %{pl}, {j}",
                            payload_type_llvm(vdef, self.structs, self.enums)
                        )
                        .unwrap();
                        self.emit_print_value(
                            &runtime_ty_from_surface(sty),
                            &format!("%{fv}"),
                            false,
                        );
                    }
                    if newline {
                        writeln!(
                            self.out,
                            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.obj_close_ln, i32 3)"
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            self.out,
                            "  call i32 (ptr, ...) @printf(ptr @nialang.std.txt.obj_close, i32 2)"
                        )
                        .unwrap();
                    }
                }
            }
            writeln!(self.out, "  br label %{cont_lbl}").unwrap();
        }
        writeln!(self.out, "{cont_lbl}:").unwrap();
    }

    fn emit_print_value(&mut self, ty: &RuntimeTy, val: &str, newline: bool) {
        self.emit_println(ty, val, newline);
    }
}

fn emit_fn(
    f: &ErasedFn,
    structs: &[StructDef],
    enums: &[EnumDef],
    fn_rets: &std::collections::HashMap<String, RuntimeTy>,
    strings: &[String],
) -> String {
    Emitter::new(structs, enums, fn_rets, strings).emit_fn(f)
}

fn surface_field_ty(sdef: &StructDef, index: usize) -> RuntimeTy {
    runtime_ty_from_surface(&sdef.fields[index].1)
}

fn runtime_ty_from_surface(ty: &crate::frontend::surface::SurfaceTy) -> RuntimeTy {
    use crate::frontend::surface::SurfaceTy;
    match ty {
        SurfaceTy::I8 => RuntimeTy::I8,
        SurfaceTy::U8 => RuntimeTy::U8,
        SurfaceTy::I16 => RuntimeTy::I16,
        SurfaceTy::U16 => RuntimeTy::U16,
        SurfaceTy::I32 => RuntimeTy::I32,
        SurfaceTy::I64 => RuntimeTy::I64,
        SurfaceTy::U64 => RuntimeTy::U64,
        SurfaceTy::I128 => RuntimeTy::I128,
        SurfaceTy::U128 => RuntimeTy::U128,
        SurfaceTy::Bool => RuntimeTy::Bool,
        SurfaceTy::F16 => RuntimeTy::F16,
        SurfaceTy::F32 => RuntimeTy::F32,
        SurfaceTy::F64 => RuntimeTy::F64,
        SurfaceTy::String => RuntimeTy::String,
        SurfaceTy::Struct(n) => RuntimeTy::Struct(n.clone()),
        SurfaceTy::Enum(n) => RuntimeTy::Enum(n.clone()),
        other => panic!("unsupported runtime surface type: {other:?}"),
    }
}

fn variant_binding_tys(vdef: &crate::frontend::surface::EnumVariantDef) -> Vec<RuntimeTy> {
    match &vdef.fields {
        EnumVariantFields::Unit => vec![],
        EnumVariantFields::Tuple(ts) => ts.iter().map(runtime_ty_from_surface).collect(),
        EnumVariantFields::Struct(fs) => fs.iter().map(|(_, t)| runtime_ty_from_surface(t)).collect(),
    }
}

fn payload_type_llvm(
    vdef: &crate::frontend::surface::EnumVariantDef,
    structs: &[StructDef],
    enums: &[EnumDef],
) -> String {
    match &vdef.fields {
        EnumVariantFields::Unit => "i8".into(),
        EnumVariantFields::Tuple(ts) if ts.len() == 1 => {
            llvm_ty(&runtime_ty_from_surface(&ts[0]), structs, enums)
        }
        EnumVariantFields::Tuple(ts) => {
            let inner = ts
                .iter()
                .map(|t| llvm_ty(&runtime_ty_from_surface(t), structs, enums))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {inner} }}")
        }
        EnumVariantFields::Struct(fs) => {
            let inner = fs
                .iter()
                .map(|(_, t)| llvm_ty(&runtime_ty_from_surface(t), structs, enums))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {inner} }}")
        }
    }
}

fn truncate_int(value: i128, ty: &RuntimeTy) -> String {
    match ty {
        RuntimeTy::I8 => format!("{}", value as i8 as i32),
        RuntimeTy::U8 => format!("{}", value as u8 as u32),
        RuntimeTy::I16 => format!("{}", value as i16 as i32),
        RuntimeTy::U16 => format!("{}", value as u16 as u32),
        RuntimeTy::I32 => format!("{}", value as i32),
        RuntimeTy::I64 => format!("{value}"),
        RuntimeTy::U64 => format!("{}", value as u64),
        RuntimeTy::I128 | RuntimeTy::U128 => format!("{value}"),
        _ => format!("{value}"),
    }
}

fn is_float_ty(ty: &RuntimeTy) -> bool {
    matches!(ty, RuntimeTy::F16 | RuntimeTy::F32 | RuntimeTy::F64)
}

fn float_binop_inst(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "fadd",
        BinOp::Sub => "fsub",
        BinOp::Mul => "fmul",
        BinOp::Div => "fdiv",
        _ => panic!("unsupported float binop"),
    }
}

fn float_cmp_inst(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Lt => "fcmp olt",
        CmpOp::Gt => "fcmp ogt",
    }
}

fn format_float_literal(value: f64, ty: &RuntimeTy) -> String {
    match ty {
        RuntimeTy::F16 => {
            let bits = f64_to_f16_bits(value);
            format!("0xH{bits:04X}")
        }
        RuntimeTy::F32 => {
            let v = value as f32;
            if v.fract() == 0.0 && v.abs() < 1e10 {
                format!("{v:.1}")
            } else {
                format!("{v:e}")
            }
        }
        RuntimeTy::F64 => {
            if value.fract() == 0.0 && value.abs() < 1e10 {
                format!("{value:.1}")
            } else {
                format!("{value:e}")
            }
        }
        _ => format!("{value}"),
    }
}

fn f64_to_f16_bits(value: f64) -> u16 {
    let v = value as f32;
    let bits = v.to_bits();
    let sign = (bits >> 31) & 1;
    let exp = ((bits >> 23) & 0xff) as i32 - 127;
    let frac = bits & 0x7fffff;
    if exp > 15 {
        return ((sign as u16) << 15) | 0x7c00;
    }
    if exp < -14 {
        return (sign as u16) << 15;
    }
    let he = (exp + 15) as u16;
    let hf = (frac >> 13) as u16;
    (sign as u16) << 15 | he << 10 | hf
}

fn emit_string_literals(strings: &[String]) -> String {
    let mut out = String::new();
    for (i, s) in strings.iter().enumerate() {
        let mut bytes = s.as_bytes().to_vec();
        bytes.push(0);
        let lit = llvm_c_escape(&bytes);
        writeln!(
            out,
            "@nialang.strlit.{i} = private unnamed_addr constant [{} x i8] c\"{lit}\", align 1",
            bytes.len()
        )
        .unwrap();
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

fn llvm_c_escape(bytes: &[u8]) -> String {
    let mut s = String::new();
    for &b in bytes {
        match b {
            b'\\' => s.push_str("\\5C"),
            b'"' => s.push_str("\\22"),
            0x20..=0x7e => s.push(char::from(b)),
            _ => {
                let _ = write!(s, "\\{:02X}", b);
            }
        }
    }
    s
}

const STRCMP_DEF: &str = r#"define i32 @strcmp(ptr %a, ptr %b) {
entry:
  br label %loop

loop:
  %idx = phi i64 [ 0, %entry ], [ %next, %same_nonzero ]
  %ap = getelementptr i8, ptr %a, i64 %idx
  %bp = getelementptr i8, ptr %b, i64 %idx
  %av = load i8, ptr %ap, align 1
  %bv = load i8, ptr %bp, align 1
  %eq = icmp eq i8 %av, %bv
  br i1 %eq, label %same, label %diff

same:
  %zero = icmp eq i8 %av, 0
  br i1 %zero, label %ret_zero, label %same_nonzero

same_nonzero:
  %next = add i64 %idx, 1
  br label %loop

diff:
  %av32 = zext i8 %av to i32
  %bv32 = zext i8 %bv to i32
  %res = sub i32 %av32, %bv32
  ret i32 %res

ret_zero:
  ret i32 0
}

"#;

fn int_binop_inst(op: BinOp, ty: &RuntimeTy) -> &'static str {
    let signed = matches!(ty, RuntimeTy::I8 | RuntimeTy::I16 | RuntimeTy::I32 | RuntimeTy::I64 | RuntimeTy::I128);
    match (op, signed) {
        (BinOp::Add, true) => "add nsw",
        (BinOp::Add, false) => "add",
        (BinOp::Sub, true) => "sub nsw",
        (BinOp::Sub, false) => "sub",
        (BinOp::Mul, true) => "mul nsw",
        (BinOp::Mul, false) => "mul",
        (BinOp::Div, true) => "sdiv",
        (BinOp::Div, false) => "udiv",
        (BinOp::Rem, true) => "srem",
        (BinOp::Rem, false) => "urem",
        (BinOp::BitAnd, _) => "and",
        (BinOp::BitOr, _) => "or",
        (BinOp::BitXor, _) => "xor",
        (BinOp::Shl, _) => "shl",
        (BinOp::Shr, true) => "ashr",
        (BinOp::Shr, false) => "lshr",
    }
}

fn llvm_ty(ty: &RuntimeTy, structs: &[StructDef], enums: &[EnumDef]) -> String {
    match ty {
        RuntimeTy::I8 => "i8".into(),
        RuntimeTy::U8 => "i8".into(),
        RuntimeTy::I16 => "i16".into(),
        RuntimeTy::U16 => "i16".into(),
        RuntimeTy::I32 => "i32".into(),
        RuntimeTy::I64 => "i64".into(),
        RuntimeTy::U64 => "i64".into(),
        RuntimeTy::I128 => "i128".into(),
        RuntimeTy::U128 => "i128".into(),
        RuntimeTy::Bool => "i1".into(),
        RuntimeTy::F16 => "half".into(),
        RuntimeTy::F32 => "float".into(),
        RuntimeTy::F64 => "double".into(),
        RuntimeTy::String => "ptr".into(),
        RuntimeTy::Unit => "i32".into(),
        RuntimeTy::Struct(name) => format!("%struct.{}", sanitize(name)),
        RuntimeTy::Enum(name) => format!("%enum.{}", sanitize(name)),
        RuntimeTy::Array { elem, len } => {
            format!("[{} x {}]", len, llvm_ty(elem, structs, enums))
        }
        RuntimeTy::Ptr(_) | RuntimeTy::Matrix { .. } => "ptr".into(),
        RuntimeTy::Qubit | RuntimeTy::Result => {
            panic!("quantum types require the QIR backend (`-q`)")
        }
    }
}

fn struct_type_decl(s: &StructDef) -> String {
    let parts: Vec<String> = s
        .fields
        .iter()
        .map(|(_, t)| llvm_ty(&runtime_ty_from_surface(t), &[], &[]))
        .collect();
    format!("%struct.{} = type {{ {} }}", sanitize(&s.name), parts.join(", "))
}

fn enum_type_decl(e: &EnumDef, structs: &[StructDef]) -> String {
    let mut parts = vec!["i32".to_string()];
    for v in &e.variants {
        parts.push(enum_variant_payload_ty(v, structs));
    }
    format!("%enum.{} = type {{ {} }}", sanitize(&e.name), parts.join(", "))
}

fn enum_variant_payload_ty(v: &crate::frontend::surface::EnumVariantDef, structs: &[StructDef]) -> String {
    match &v.fields {
        EnumVariantFields::Unit => "i8".into(),
        EnumVariantFields::Tuple(ts) if ts.len() == 1 => {
            llvm_ty(&runtime_ty_from_surface(&ts[0]), structs, &[])
        }
        EnumVariantFields::Tuple(ts) => {
            let inner = ts
                .iter()
                .map(|t| llvm_ty(&runtime_ty_from_surface(t), structs, &[]))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {inner} }}")
        }
        EnumVariantFields::Struct(fs) => {
            let inner = fs
                .iter()
                .map(|(_, t)| llvm_ty(&runtime_ty_from_surface(t), structs, &[]))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {inner} }}")
        }
    }
}

fn emit_struct_print_constants(structs: &[StructDef]) -> String {
    let mut out = String::new();
    for s in structs.iter().filter(|s| !s.is_tuple) {
        for (fname, _) in &s.fields {
            let key = format!("\"{fname}\": ");
            let bytes = key.as_bytes();
            let sz = bytes.len() + 1;
            let lit = llvm_c_escape(bytes);
            let sym = struct_field_key_symbol(&s.name, fname);
            writeln!(
                out,
                "@{sym} = private unnamed_addr constant [{sz} x i8] c\"{lit}\\00\", align 1"
            )
            .unwrap();
        }
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

fn struct_field_key_symbol(sname: &str, fname: &str) -> String {
    format!(
        "nialang.std.txt.json.key.{}.{}",
        sanitize(sname),
        sanitize(fname)
    )
}

fn emit_enum_print_constants(enums: &[EnumDef]) -> String {
    let mut out = String::new();
    for e in enums {
        for v in &e.variants {
            let prefix = format!("{}: ", v.name);
            let bytes = prefix.as_bytes();
            let sz = bytes.len() + 1;
            let lit = llvm_c_escape(bytes);
            let sym = enum_variant_prefix_symbol(&e.name, &v.name);
            writeln!(
                out,
                "@{sym} = private unnamed_addr constant [{sz} x i8] c\"{lit}\\00\", align 1"
            )
            .unwrap();
            if let EnumVariantFields::Struct(fs) = &v.fields {
                for (fname, _) in fs {
                    let key = format!("\"{fname}\": ");
                    let bytes = key.as_bytes();
                    let sz = bytes.len() + 1;
                    let lit = llvm_c_escape(bytes);
                    let sym = enum_struct_field_key_symbol(&e.name, &v.name, fname);
                    writeln!(
                        out,
                        "@{sym} = private unnamed_addr constant [{sz} x i8] c\"{lit}\\00\", align 1"
                    )
                    .unwrap();
                }
            }
        }
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

fn enum_variant_prefix_symbol(enum_name: &str, variant: &str) -> String {
    format!(
        "nialang.enum.{}.{}",
        sanitize(enum_name),
        sanitize(variant)
    )
}

fn enum_struct_field_key_symbol(enum_name: &str, variant: &str, field: &str) -> String {
    format!(
        "nialang.enum.{}.{}.key.{}",
        sanitize(enum_name),
        sanitize(variant),
        sanitize(field)
    )
}
