use std::collections::HashMap;
use std::fmt::Write as _;

use crate::ast::{Expr, FnDef, Stmt, StructDef, Ty};
use crate::typecheck::FnSig;

pub fn emit_module(structs: &[StructDef], fns: &[FnDef], fn_sigs: &HashMap<String, FnSig>) -> String {
    let mut out = String::new();
    out.push_str("; generated by nialang\n");
    out.push_str("target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\"\n");
    out.push_str("target triple = \"unknown-unknown-unknown\"\n\n");

    for s in structs {
        out.push_str(&struct_type_decl(s));
        out.push('\n');
    }
    if !structs.is_empty() {
        out.push('\n');
    }

    for f in fns {
        out.push_str(&emit_fn(f, structs, fn_sigs));
        out.push('\n');
    }
    out
}

fn llvm_ty(t: &Ty, _structs: &[StructDef]) -> String {
    match t {
        Ty::I32 => "i32".into(),
        Ty::U128 => "i128".into(),
        Ty::Struct(n) => format!("%struct.{}", sanitize(n)),
    }
}

fn struct_type_decl(s: &StructDef) -> String {
    let parts: Vec<String> = s
        .fields
        .iter()
        .map(|(_, t)| llvm_ty(t, &[]))
        .collect();
    format!(
        "%struct.{} = type {{ {} }}",
        sanitize(&s.name),
        parts.join(", ")
    )
}

fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

struct Gen<'a> {
    structs: &'a [StructDef],
    fn_sigs: &'a HashMap<String, FnSig>,
    tmp: u32,
    out: String,
}

impl<'a> Gen<'a> {
    fn new(structs: &'a [StructDef], fn_sigs: &'a HashMap<String, FnSig>) -> Self {
        Self {
            structs,
            fn_sigs,
            tmp: 0,
            out: String::new(),
        }
    }

    fn fresh(&mut self) -> String {
        let n = self.tmp;
        self.tmp += 1;
        format!("t{n}")
    }

    fn struct_idx(&self, sname: &str, field: &str) -> Option<u32> {
        let s = self.structs.iter().find(|s| s.name == sname)?;
        s.fields
            .iter()
            .position(|(n, _)| n == field)
            .map(|i| i as u32)
    }

    fn emit_fn(mut self, f: &FnDef) -> String {
        self.out.clear();
        let ret_ll = match &f.ret {
            None => "void".into(),
            Some(t) => llvm_ty(t, self.structs),
        };
        let mut params = Vec::new();
        for (pname, pty) in f.params.iter() {
            let ll = llvm_ty(pty, self.structs);
            let ps = sanitize(pname);
            params.push(format!("{ll} %{ps}"));
        }
        writeln!(
            self.out,
            "define {} @{}({}) {{",
            ret_ll,
            sanitize(&f.name),
            params.join(", ")
        )
        .unwrap();
        writeln!(self.out, "entry:").unwrap();

        let mut local_ptr: HashMap<String, (Ty, String)> = HashMap::new();
        for (pname, pty) in f.params.iter() {
            let ps = sanitize(pname);
            let ptr = format!("%{ps}.addr");
            writeln!(
                self.out,
                "  {} = alloca {}",
                ptr,
                llvm_ty(pty, self.structs)
            )
            .unwrap();
            writeln!(
                self.out,
                "  store {} %{ps}, ptr {}",
                llvm_ty(pty, self.structs),
                ptr
            )
            .unwrap();
            local_ptr.insert(pname.clone(), (pty.clone(), ptr));
        }

        for st in &f.body.stmts {
            let Stmt::Let { name, ty, init } = st;
            let (t, v) = self.emit_expr(init, &local_ptr, ty.as_ref());
            let ptr = format!("%{}.addr", sanitize(name));
            writeln!(self.out, "  {} = alloca {}", ptr, llvm_ty(&t, self.structs)).unwrap();
            writeln!(
                self.out,
                "  store {} {}, ptr {}",
                llvm_ty(&t, self.structs),
                v,
                ptr
            )
            .unwrap();
            local_ptr.insert(name.clone(), (t, ptr));
        }

        if let Some(ret_ty) = &f.ret {
            let tail = f.body.tail.as_ref().unwrap();
            let (t, v) = self.emit_expr(tail, &local_ptr, Some(ret_ty));
            debug_assert!(types_match(&t, ret_ty));
            writeln!(
                self.out,
                "  ret {} {}",
                llvm_ty(ret_ty, self.structs),
                v
            )
            .unwrap();
        } else {
            writeln!(self.out, "  ret void").unwrap();
        }

        writeln!(self.out, "}}").unwrap();
        self.out
    }

    fn emit_expr(
        &mut self,
        e: &Expr,
        locals: &HashMap<String, (Ty, String)>,
        hint: Option<&Ty>,
    ) -> (Ty, String) {
        match e {
            Expr::Int(n) => match hint {
                Some(Ty::U128) => (Ty::U128, format!("{n}")),
                Some(Ty::I32) | None => (Ty::I32, format!("{n}")),
                Some(Ty::Struct(_)) => unreachable!("typechecked"),
            },
            Expr::Ident(name) => {
                let (ty, ptr) = locals.get(name).expect("checked var");
                let tmp = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = load {}, ptr {}",
                    tmp,
                    llvm_ty(ty, self.structs),
                    ptr
                )
                .unwrap();
                (ty.clone(), format!("%{tmp}"))
            }
            Expr::Add(l, r) => {
                let (tl, vl) = self.emit_expr(l, locals, None);
                let (tr, vr) = self.emit_expr(r, locals, Some(&tl));
                assert!(types_match(&tl, &tr));
                let tmp = self.fresh();
                match tl {
                    Ty::I32 => {
                        writeln!(self.out, "  %{} = add nsw i32 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::U128 => {
                        writeln!(self.out, "  %{} = add i128 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::Struct(_) => unreachable!("add on struct"),
                }
                (tl, format!("%{tmp}"))
            }
            Expr::Call { name, args } => {
                let sig = self.fn_sigs.get(name).unwrap();
                let mut arg_strs = Vec::new();
                for (a, pt) in args.iter().zip(&sig.params) {
                    let (at, av) = self.emit_expr(a, locals, Some(pt));
                    debug_assert!(types_match(&at, pt));
                    arg_strs.push(format!("{} {}", llvm_ty(pt, self.structs), av));
                }
                let ret_ty = sig.ret.clone().unwrap();
                let tmp = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = call {} @{}({})",
                    tmp,
                    llvm_ty(&ret_ty, self.structs),
                    sanitize(name),
                    arg_strs.join(", ")
                )
                .unwrap();
                (ret_ty, format!("%{tmp}"))
            }
            Expr::StructLit { name, fields } => {
                let sdef = self.structs.iter().find(|s| s.name == *name).unwrap();
                let llvm_st = format!("%struct.{}", sanitize(name));
                let mut agg = "poison".to_string();
                for (i, (fname, _)) in sdef.fields.iter().enumerate() {
                    let (_, fe) = fields.iter().find(|(n, _)| n == fname).unwrap();
                    let fty = sdef.fields[i].1.clone();
                    let (ft, fv) = self.emit_expr(fe, locals, Some(&fty));
                    let tmp = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = insertvalue {} {}, {} {}, {}",
                        tmp,
                        llvm_st,
                        agg,
                        llvm_ty(&ft, self.structs),
                        fv,
                        i
                    )
                    .unwrap();
                    agg = format!("%{tmp}");
                }
                let sname = name.clone();
                let tmp = self.fresh();
                writeln!(self.out, "  %{} = alloca {}", tmp, llvm_st).unwrap();
                writeln!(
                    self.out,
                    "  store {} {}, ptr %{}",
                    llvm_st, agg, tmp
                )
                .unwrap();
                let loadt = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = load {}, ptr %{}",
                    loadt,
                    llvm_st,
                    tmp
                )
                .unwrap();
                (Ty::Struct(sname), format!("%{loadt}"))
            }
            Expr::Field(obj, fname) => {
                let (bt, bv) = self.emit_expr(obj, locals, None);
                let Ty::Struct(sname) = bt else {
                    unreachable!()
                };
                let idx = self.struct_idx(&sname, fname).unwrap();
                let llvm_st = format!("%struct.{}", sanitize(&sname));
                let tmp = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = extractvalue {} {}, {}",
                    tmp, llvm_st, bv, idx
                )
                .unwrap();
                let fty = self
                    .structs
                    .iter()
                    .find(|s| s.name == sname)
                    .unwrap()
                    .fields
                    .iter()
                    .find(|(n, _)| n == fname)
                    .unwrap()
                    .1
                    .clone();
                (fty, format!("%{tmp}"))
            }
        }
    }
}

fn types_match(a: &Ty, b: &Ty) -> bool {
    match (a, b) {
        (Ty::I32, Ty::I32) | (Ty::U128, Ty::U128) => true,
        (Ty::Struct(x), Ty::Struct(y)) => x == y,
        _ => false,
    }
}

fn emit_fn(f: &FnDef, structs: &[StructDef], fn_sigs: &HashMap<String, FnSig>) -> String {
    Gen::new(structs, fn_sigs).emit_fn(f)
}
