use std::collections::HashMap;
use std::fmt::Write as _;

use crate::ast::{Expr, FnDef, Stmt, StructDef, Ty};
use crate::nia_std::PRINTLN;
use crate::typecheck::FnSig;

pub fn emit_module(
    structs: &[StructDef],
    fns: &[FnDef],
    fn_sigs: &HashMap<String, FnSig>,
) -> String {
    let mut out = String::new();
    out.push_str("; generated by nialang\n");
    out.push_str("target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\"\n");
    out.push_str("target triple = \"unknown-unknown-unknown\"\n\n");
    out.push_str(crate::nia_std::llvm_prelude());
    out.push_str(&emit_struct_print_constants(structs));

    for s in structs {
        out.push_str(&struct_type_decl(s));
        out.push('\n');
    }
    if !structs.is_empty() {
        out.push('\n');
    }

    for f in fns {
        out.push_str(&emit_fn(f, structs, fn_sigs));
        out.push('\n');
    }
    out
}

fn llvm_c_escape(bytes: &[u8]) -> String {
    let mut s = String::new();
    for &b in bytes {
        match b {
            b'\\' => s.push_str("\\5C"),
            b'"' => s.push_str("\\22"),
            0x20..=0x7e => s.push(char::from(b)),
            _ => {
                let _ = write!(s, "\\{:02X}", b);
            }
        }
    }
    s
}

fn struct_field_key_symbol(sname: &str, fname: &str) -> String {
    format!(
        "nialang.std.txt.json.key.{}.{}",
        sanitize(sname),
        sanitize(fname)
    )
}

fn emit_struct_print_constants(structs: &[StructDef]) -> String {
    let mut out = String::new();
    for s in structs.iter().filter(|s| !s.is_tuple) {
        for (fname, _) in &s.fields {
            let key = format!("\"{}\": ", fname);
            let bytes = key.as_bytes();
            let sz = bytes.len() + 1;
            let lit = llvm_c_escape(bytes);
            let sym = struct_field_key_symbol(&s.name, fname);
            writeln!(
                out,
                "@{} = private unnamed_addr constant [{} x i8] c\"{}\\00\", align 1",
                sym, sz, lit
            )
            .unwrap();
        }
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

fn llvm_ty(t: &Ty, _structs: &[StructDef]) -> String {
    match t {
        Ty::I8 => "i8".into(),
        Ty::U8 => "i8".into(),
        Ty::I16 => "i16".into(),
        Ty::U16 => "i16".into(),
        Ty::I32 => "i32".into(),
        Ty::I64 => "i64".into(),
        Ty::U64 => "i64".into(),
        Ty::I128 => "i128".into(),
        Ty::Isize => "i64".into(),
        Ty::Usize => "i64".into(),
        Ty::U128 => "i128".into(),
        Ty::Bool => "i1".into(),
        Ty::Array(elem, n) => format!("[{} x {}]", n, llvm_ty(elem, _structs)),
        Ty::Struct(n) => format!("%struct.{}", sanitize(n)),
        Ty::Ptr(_) => "ptr".into(),
        Ty::Unit => "void".into(),
    }
}

fn struct_type_decl(s: &StructDef) -> String {
    let parts: Vec<String> = s.fields.iter().map(|(_, t)| llvm_ty(t, &[])).collect();
    format!(
        "%struct.{} = type {{ {} }}",
        sanitize(&s.name),
        parts.join(", ")
    )
}

fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

struct Gen<'a> {
    structs: &'a [StructDef],
    fn_sigs: &'a HashMap<String, FnSig>,
    tmp: u32,
    lbl: u32,
    out: String,
    terminated: bool,
}

impl<'a> Gen<'a> {
    fn new(structs: &'a [StructDef], fn_sigs: &'a HashMap<String, FnSig>) -> Self {
        Self {
            structs,
            fn_sigs,
            tmp: 0,
            lbl: 0,
            out: String::new(),
            terminated: false,
        }
    }

    fn fresh(&mut self) -> String {
        let n = self.tmp;
        self.tmp += 1;
        format!("t{n}")
    }

    fn fresh_label(&mut self, prefix: &str) -> String {
        let n = self.lbl;
        self.lbl += 1;
        format!("{prefix}.{n}")
    }

    fn fmt_ptr(&mut self, sym: &str, size: u32) -> String {
        let tmp = self.fresh();
        writeln!(
            self.out,
            "  %{} = getelementptr inbounds [{} x i8], ptr @{}, i64 0, i64 0",
            tmp, size, sym
        )
        .unwrap();
        format!("%{tmp}")
    }

    fn emit_printf_text(&mut self, sym: &str, size: u32) {
        let p = self.fmt_ptr(sym, size);
        writeln!(self.out, "  call i32 (ptr, ...) @printf(ptr {})", p).unwrap();
    }

    fn emit_printf_text_dynamic(&mut self, sym: &str, size: usize) {
        self.emit_printf_text(sym, size as u32);
    }

    fn struct_def(&self, name: &str) -> Option<&StructDef> {
        self.structs.iter().find(|s| s.name == name)
    }

    fn emit_print_primitive(&mut self, ty: &Ty, v: &str, newline: bool) {
        match ty {
            Ty::I8 => {
                let t = self.fresh();
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.i32", 4)
                } else {
                    ("nialang.std.fmt.i32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(self.out, "  %{} = sext i8 {} to i32", t, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 %{})",
                    p, t
                )
                .unwrap();
            }
            Ty::U8 => {
                let t = self.fresh();
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.u32", 4)
                } else {
                    ("nialang.std.fmt.u32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(self.out, "  %{} = zext i8 {} to i32", t, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 %{})",
                    p, t
                )
                .unwrap();
            }
            Ty::I16 => {
                let t = self.fresh();
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.i32", 4)
                } else {
                    ("nialang.std.fmt.i32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(self.out, "  %{} = sext i16 {} to i32", t, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 %{})",
                    p, t
                )
                .unwrap();
            }
            Ty::U16 => {
                let t = self.fresh();
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.u32", 4)
                } else {
                    ("nialang.std.fmt.u32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(self.out, "  %{} = zext i16 {} to i32", t, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 %{})",
                    p, t
                )
                .unwrap();
            }
            Ty::I32 => {
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.i32", 4)
                } else {
                    ("nialang.std.fmt.i32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 {})",
                    p, v
                )
                .unwrap();
            }
            Ty::I64 | Ty::Isize => {
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.i64", 6)
                } else {
                    ("nialang.std.fmt.i64.nn", 5)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i64 {})",
                    p, v
                )
                .unwrap();
            }
            Ty::U64 | Ty::Usize => {
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.u64", 6)
                } else {
                    ("nialang.std.fmt.u64.nn", 5)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i64 {})",
                    p, v
                )
                .unwrap();
            }
            Ty::Bool => {
                let t = self.fresh();
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.u32", 4)
                } else {
                    ("nialang.std.fmt.u32.nn", 3)
                };
                let p = self.fmt_ptr(sym, sz);
                writeln!(self.out, "  %{} = zext i1 {} to i32", t, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i32 %{})",
                    p, t
                )
                .unwrap();
            }
            Ty::I128 | Ty::U128 => {
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.i128hex", 18)
                } else {
                    ("nialang.std.fmt.i128hex.nn", 17)
                };
                let p = self.fmt_ptr(sym, sz);
                let hi128 = self.fresh();
                let hi64 = self.fresh();
                let lo64 = self.fresh();
                writeln!(self.out, "  %{} = lshr i128 {}, 64", hi128, v).unwrap();
                writeln!(self.out, "  %{} = trunc i128 %{} to i64", hi64, hi128).unwrap();
                writeln!(self.out, "  %{} = trunc i128 {} to i64", lo64, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i64 %{}, i64 %{})",
                    p, hi64, lo64
                )
                .unwrap();
            }
            Ty::Ptr(_) => {
                let (sym, sz) = if newline {
                    ("nialang.std.fmt.ptrhex", 8)
                } else {
                    ("nialang.std.fmt.ptrhex.nn", 7)
                };
                let p = self.fmt_ptr(sym, sz);
                let addr = self.fresh();
                writeln!(self.out, "  %{} = ptrtoint ptr {} to i64", addr, v).unwrap();
                writeln!(
                    self.out,
                    "  call i32 (ptr, ...) @printf(ptr {}, i64 %{})",
                    p, addr
                )
                .unwrap();
            }
            Ty::Array(_, _) | Ty::Struct(_) | Ty::Unit => unreachable!("typechecked"),
        }
    }

    fn emit_print_array(&mut self, elem_ty: &Ty, n: usize, arr_v: &str, newline: bool) {
        self.emit_printf_text("nialang.std.txt.arr_open", 2);
        for i in 0..n {
            if i > 0 {
                self.emit_printf_text("nialang.std.txt.arr_sep", 3);
            }
            let ev = self.fresh();
            let llvm_arr = format!("[{} x {}]", n, llvm_ty(elem_ty, self.structs));
            writeln!(
                self.out,
                "  %{} = extractvalue {} {}, {}",
                ev, llvm_arr, arr_v, i
            )
            .unwrap();
            self.emit_print_value(elem_ty, &format!("%{ev}"), false);
        }
        if newline {
            self.emit_printf_text("nialang.std.txt.arr_close_ln", 3);
        } else {
            self.emit_printf_text("nialang.std.txt.arr_close", 2);
        }
    }

    fn emit_print_struct(&mut self, sname: &str, struct_v: &str, newline: bool) {
        let sdef = self.struct_def(sname).expect("typechecked struct");
        let is_tuple = sdef.is_tuple;
        let fields = sdef.fields.clone();
        if is_tuple {
            self.emit_printf_text("nialang.std.txt.tuple_open", 2);
            for (i, (_, fty)) in fields.iter().enumerate() {
                if i > 0 {
                    self.emit_printf_text("nialang.std.txt.arr_sep", 3);
                }
                let fv = self.fresh();
                let llvm_st = format!("%struct.{}", sanitize(sname));
                writeln!(
                    self.out,
                    "  %{} = extractvalue {} {}, {}",
                    fv, llvm_st, struct_v, i
                )
                .unwrap();
                self.emit_print_value(fty, &format!("%{fv}"), false);
            }
            if newline {
                self.emit_printf_text("nialang.std.txt.tuple_close_ln", 3);
            } else {
                self.emit_printf_text("nialang.std.txt.tuple_close", 2);
            }
            return;
        }

        self.emit_printf_text("nialang.std.txt.obj_open", 2);
        for (i, (fname, fty)) in fields.iter().enumerate() {
            if i > 0 {
                self.emit_printf_text("nialang.std.txt.arr_sep", 3);
            }
            let key_sym = struct_field_key_symbol(sname, fname);
            let key_sz = fname.as_bytes().len() + 5;
            self.emit_printf_text_dynamic(&key_sym, key_sz);
            let fv = self.fresh();
            let llvm_st = format!("%struct.{}", sanitize(sname));
            writeln!(
                self.out,
                "  %{} = extractvalue {} {}, {}",
                fv, llvm_st, struct_v, i
            )
            .unwrap();
            self.emit_print_value(fty, &format!("%{fv}"), false);
        }
        if newline {
            self.emit_printf_text("nialang.std.txt.obj_close_ln", 3);
        } else {
            self.emit_printf_text("nialang.std.txt.obj_close", 2);
        }
    }

    fn emit_print_value(&mut self, ty: &Ty, v: &str, newline: bool) {
        match ty {
            Ty::Array(elem, n) => {
                self.emit_print_array(elem, *n, v, newline);
            }
            Ty::Struct(sname) => {
                self.emit_print_struct(sname, v, newline);
            }
            _ => self.emit_print_primitive(ty, v, newline),
        }
    }

    fn struct_idx(&self, sname: &str, field: &str) -> Option<u32> {
        let s = self.structs.iter().find(|s| s.name == sname)?;
        s.fields
            .iter()
            .position(|(n, _)| n == field)
            .map(|i| i as u32)
    }

    fn emit_fn(mut self, f: &FnDef) -> String {
        self.out.clear();
        let ret_ll = match &f.ret {
            None => "void".into(),
            Some(t) => llvm_ty(t, self.structs),
        };
        let mut params = Vec::new();
        for (pname, pty) in f.params.iter() {
            let ll = llvm_ty(pty, self.structs);
            let ps = sanitize(pname);
            params.push(format!("{ll} %{ps}"));
        }
        writeln!(
            self.out,
            "define {} @{}({}) {{",
            ret_ll,
            sanitize(&f.name),
            params.join(", ")
        )
        .unwrap();
        writeln!(self.out, "entry:").unwrap();

        let mut local_ptr: HashMap<String, (Ty, String)> = HashMap::new();
        for (pname, pty) in f.params.iter() {
            let ps = sanitize(pname);
            let ptr = format!("%{ps}.addr");
            writeln!(
                self.out,
                "  {} = alloca {}",
                ptr,
                llvm_ty(pty, self.structs)
            )
            .unwrap();
            writeln!(
                self.out,
                "  store {} %{ps}, ptr {}",
                llvm_ty(pty, self.structs),
                ptr
            )
            .unwrap();
            local_ptr.insert(pname.clone(), (pty.clone(), ptr));
        }

        for st in &f.body.stmts {
            self.emit_stmt(st, &mut local_ptr, f.ret.as_ref());
            if self.terminated {
                break;
            }
        }

        if self.terminated {
            writeln!(self.out, "}}").unwrap();
            return self.out;
        }

        if let Some(ret_ty) = &f.ret {
            let tail = f.body.tail.as_ref().unwrap();
            let (t, v) = self.emit_expr(tail, &local_ptr, Some(ret_ty));
            debug_assert!(types_match(&t, ret_ty));
            writeln!(self.out, "  ret {} {}", llvm_ty(ret_ty, self.structs), v).unwrap();
        } else {
            writeln!(self.out, "  ret void").unwrap();
        }

        writeln!(self.out, "}}").unwrap();
        self.out
    }

    fn emit_stmt(
        &mut self,
        st: &Stmt,
        locals: &mut HashMap<String, (Ty, String)>,
        fn_ret: Option<&Ty>,
    ) {
        match st {
            Stmt::Let { name, ty, init } => {
                let (t, v) = self.emit_expr(init, locals, ty.as_ref());
                let ptr = format!("%{}.addr", sanitize(name));
                writeln!(self.out, "  {} = alloca {}", ptr, llvm_ty(&t, self.structs)).unwrap();
                writeln!(
                    self.out,
                    "  store {} {}, ptr {}",
                    llvm_ty(&t, self.structs),
                    v,
                    ptr
                )
                .unwrap();
                locals.insert(name.clone(), (t, ptr));
            }
            Stmt::Expr(e) => {
                self.emit_expr(e, locals, None);
            }
            Stmt::Return(e) => {
                let Some(ret_ty) = fn_ret else {
                    unreachable!("typechecked")
                };
                let (t, v) = self.emit_expr(e, locals, Some(ret_ty));
                debug_assert!(types_match(&t, ret_ty));
                writeln!(self.out, "  ret {} {}", llvm_ty(ret_ty, self.structs), v).unwrap();
                self.terminated = true;
            }
            Stmt::If { cond, then_block } => {
                let (ct, cv) = self.emit_expr(cond, locals, Some(&Ty::Bool));
                debug_assert!(matches!(ct, Ty::Bool));
                let then_lbl = self.fresh_label("if.then");
                let cont_lbl = self.fresh_label("if.cont");
                writeln!(
                    self.out,
                    "  br i1 {}, label %{}, label %{}",
                    cv, then_lbl, cont_lbl
                )
                .unwrap();
                writeln!(self.out, "{}:", then_lbl).unwrap();
                let mut then_locals = locals.clone();
                self.terminated = false;
                for st in &then_block.stmts {
                    self.emit_stmt(st, &mut then_locals, fn_ret);
                    if self.terminated {
                        break;
                    }
                }
                if !self.terminated {
                    if let Some(tail) = &then_block.tail {
                        self.emit_expr(tail, &then_locals, None);
                    }
                    writeln!(self.out, "  br label %{}", cont_lbl).unwrap();
                }
                self.terminated = false;
                writeln!(self.out, "{}:", cont_lbl).unwrap();
            }
        }
    }

    fn emit_expr(
        &mut self,
        e: &Expr,
        locals: &HashMap<String, (Ty, String)>,
        hint: Option<&Ty>,
    ) -> (Ty, String) {
        match e {
            Expr::Int(n) => match hint {
                Some(Ty::I8) => (Ty::I8, format!("{n}")),
                Some(Ty::U8) => (Ty::U8, format!("{n}")),
                Some(Ty::I16) => (Ty::I16, format!("{n}")),
                Some(Ty::U16) => (Ty::U16, format!("{n}")),
                Some(Ty::I32) | None => (Ty::I32, format!("{n}")),
                Some(Ty::I64) => (Ty::I64, format!("{n}")),
                Some(Ty::U64) => (Ty::U64, format!("{n}")),
                Some(Ty::I128) => (Ty::I128, format!("{n}")),
                Some(Ty::Isize) => (Ty::Isize, format!("{n}")),
                Some(Ty::Usize) => (Ty::Usize, format!("{n}")),
                Some(Ty::U128) => (Ty::U128, format!("{n}")),
                Some(Ty::Struct(_))
                | Some(Ty::Unit)
                | Some(Ty::Ptr(_))
                | Some(Ty::Bool)
                | Some(Ty::Array(_, _)) => {
                    unreachable!("typechecked")
                }
            },
            Expr::Bool(b) => (Ty::Bool, if *b { "1".into() } else { "0".into() }),
            Expr::Ident(name) => {
                let (ty, ptr) = locals.get(name).expect("checked var");
                let tmp = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = load {}, ptr {}",
                    tmp,
                    llvm_ty(ty, self.structs),
                    ptr
                )
                .unwrap();
                (ty.clone(), format!("%{tmp}"))
            }
            Expr::Add(l, r) => {
                let (tl, vl) = self.emit_expr(l, locals, None);
                let (tr, vr) = self.emit_expr(r, locals, Some(&tl));
                assert!(types_match(&tl, &tr));
                let tmp = self.fresh();
                match tl {
                    Ty::I8 | Ty::U8 => {
                        writeln!(self.out, "  %{} = add i8 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I16 | Ty::U16 => {
                        writeln!(self.out, "  %{} = add i16 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I32 => {
                        writeln!(self.out, "  %{} = add nsw i32 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I64 | Ty::U64 | Ty::Isize | Ty::Usize => {
                        writeln!(self.out, "  %{} = add i64 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::I128 => {
                        writeln!(self.out, "  %{} = add i128 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::U128 => {
                        writeln!(self.out, "  %{} = add i128 {}, {}", tmp, vl, vr).unwrap();
                    }
                    Ty::Array(_, _) | Ty::Struct(_) | Ty::Unit | Ty::Ptr(_) | Ty::Bool => {
                        unreachable!("add on non-numeric")
                    }
                }
                (tl, format!("%{tmp}"))
            }
            Expr::Call { name, args } => {
                if name == PRINTLN {
                    let (at, av) = self.emit_expr(&args[0], locals, None);
                    self.emit_print_value(&at, &av, true);
                    return (Ty::Unit, String::new());
                }
                if let Some(sdef) = self.structs.iter().find(|s| s.name == *name && s.is_tuple) {
                    let llvm_st = format!("%struct.{}", sanitize(name));
                    let mut agg = "poison".to_string();
                    for (i, (_, fty)) in sdef.fields.iter().enumerate() {
                        let (at, av) = self.emit_expr(&args[i], locals, Some(fty));
                        debug_assert!(types_match(&at, fty));
                        let tmp = self.fresh();
                        writeln!(
                            self.out,
                            "  %{} = insertvalue {} {}, {} {}, {}",
                            tmp,
                            llvm_st,
                            agg,
                            llvm_ty(&at, self.structs),
                            av,
                            i
                        )
                        .unwrap();
                        agg = format!("%{tmp}");
                    }
                    let sname = name.clone();
                    let tmp = self.fresh();
                    writeln!(self.out, "  %{} = alloca {}", tmp, llvm_st).unwrap();
                    writeln!(self.out, "  store {} {}, ptr %{}", llvm_st, agg, tmp).unwrap();
                    let loadt = self.fresh();
                    writeln!(self.out, "  %{} = load {}, ptr %{}", loadt, llvm_st, tmp).unwrap();
                    return (Ty::Struct(sname), format!("%{loadt}"));
                }
                let sig = self.fn_sigs.get(name).expect("unknown fn");
                let mut arg_strs = Vec::new();
                for (a, pt) in args.iter().zip(&sig.params) {
                    let (at, av) = self.emit_expr(a, locals, Some(pt));
                    debug_assert!(types_match(&at, pt));
                    arg_strs.push(format!("{} {}", llvm_ty(pt, self.structs), av));
                }
                match &sig.ret {
                    Some(ret_ty) => {
                        let tmp = self.fresh();
                        writeln!(
                            self.out,
                            "  %{} = call {} @{}({})",
                            tmp,
                            llvm_ty(ret_ty, self.structs),
                            sanitize(name),
                            arg_strs.join(", ")
                        )
                        .unwrap();
                        (ret_ty.clone(), format!("%{tmp}"))
                    }
                    None => {
                        writeln!(
                            self.out,
                            "  call void @{}({})",
                            sanitize(name),
                            arg_strs.join(", ")
                        )
                        .unwrap();
                        (Ty::Unit, String::new())
                    }
                }
            }
            Expr::StructLit { name, fields } => {
                let sdef = self.structs.iter().find(|s| s.name == *name).unwrap();
                let llvm_st = format!("%struct.{}", sanitize(name));
                let mut agg = "poison".to_string();
                for (i, (fname, _)) in sdef.fields.iter().enumerate() {
                    let (_, fe) = fields.iter().find(|(n, _)| n == fname).unwrap();
                    let fty = sdef.fields[i].1.clone();
                    let (ft, fv) = self.emit_expr(fe, locals, Some(&fty));
                    let tmp = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = insertvalue {} {}, {} {}, {}",
                        tmp,
                        llvm_st,
                        agg,
                        llvm_ty(&ft, self.structs),
                        fv,
                        i
                    )
                    .unwrap();
                    agg = format!("%{tmp}");
                }
                let sname = name.clone();
                let tmp = self.fresh();
                writeln!(self.out, "  %{} = alloca {}", tmp, llvm_st).unwrap();
                writeln!(self.out, "  store {} {}, ptr %{}", llvm_st, agg, tmp).unwrap();
                let loadt = self.fresh();
                writeln!(self.out, "  %{} = load {}, ptr %{}", loadt, llvm_st, tmp).unwrap();
                (Ty::Struct(sname), format!("%{loadt}"))
            }
            Expr::ArrayLit(elems) => {
                let (elem_ty, n) = match hint {
                    Some(Ty::Array(elem, n)) => (elem.as_ref().clone(), *n),
                    _ => {
                        let first = elems.first().expect("typechecked non-empty array");
                        let (t, _) = self.emit_expr(first, locals, None);
                        (t, elems.len())
                    }
                };
                let llvm_arr = format!("[{} x {}]", n, llvm_ty(&elem_ty, self.structs));
                let mut agg = "poison".to_string();
                for (i, e) in elems.iter().enumerate() {
                    let (et, ev) = self.emit_expr(e, locals, Some(&elem_ty));
                    debug_assert!(types_match(&et, &elem_ty));
                    let tmp = self.fresh();
                    writeln!(
                        self.out,
                        "  %{} = insertvalue {} {}, {} {}, {}",
                        tmp,
                        llvm_arr,
                        agg,
                        llvm_ty(&et, self.structs),
                        ev,
                        i
                    )
                    .unwrap();
                    agg = format!("%{tmp}");
                }
                let tmp = self.fresh();
                writeln!(self.out, "  %{} = alloca {}", tmp, llvm_arr).unwrap();
                writeln!(self.out, "  store {} {}, ptr %{}", llvm_arr, agg, tmp).unwrap();
                let loadt = self.fresh();
                writeln!(self.out, "  %{} = load {}, ptr %{}", loadt, llvm_arr, tmp).unwrap();
                (Ty::Array(Box::new(elem_ty), n), format!("%{loadt}"))
            }
            Expr::Field(obj, fname) => {
                let (bt, bv) = self.emit_expr(obj, locals, None);
                let Ty::Struct(sname) = bt else {
                    unreachable!()
                };
                let idx = self.struct_idx(&sname, fname).unwrap();
                let llvm_st = format!("%struct.{}", sanitize(&sname));
                let tmp = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = extractvalue {} {}, {}",
                    tmp, llvm_st, bv, idx
                )
                .unwrap();
                let fty = self
                    .structs
                    .iter()
                    .find(|s| s.name == sname)
                    .unwrap()
                    .fields
                    .iter()
                    .find(|(n, _)| n == fname)
                    .unwrap()
                    .1
                    .clone();
                (fty, format!("%{tmp}"))
            }
            Expr::Index(arr, idx) => {
                let (at, av) = self.emit_expr(arr, locals, None);
                let (it, iv) = self.emit_expr(idx, locals, Some(&Ty::I32));
                debug_assert!(matches!(it, Ty::I32));
                let Ty::Array(elem_ty, n) = at else {
                    unreachable!("typechecked")
                };
                let llvm_arr = format!("[{} x {}]", n, llvm_ty(&elem_ty, self.structs));
                let ptr = self.fresh();
                writeln!(self.out, "  %{} = alloca {}", ptr, llvm_arr).unwrap();
                writeln!(self.out, "  store {} {}, ptr %{}", llvm_arr, av, ptr).unwrap();
                let idx64 = self.fresh();
                writeln!(self.out, "  %{} = sext i32 {} to i64", idx64, iv).unwrap();
                let gep = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = getelementptr inbounds {}, ptr %{}, i64 0, i64 %{}",
                    gep, llvm_arr, ptr, idx64
                )
                .unwrap();
                let val = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = load {}, ptr %{}",
                    val,
                    llvm_ty(&elem_ty, self.structs),
                    gep
                )
                .unwrap();
                ((*elem_ty).clone(), format!("%{val}"))
            }
            Expr::AddrOf(inner) => {
                let Expr::Ident(name) = inner.as_ref() else {
                    unreachable!("typechecked")
                };
                let (ty, ptr) = locals.get(name).expect("checked var");
                (Ty::Ptr(Box::new(ty.clone())), ptr.clone())
            }
            Expr::Deref(inner) => {
                let (ti, v) = self.emit_expr(inner, locals, None);
                let Ty::Ptr(pointee) = ti else {
                    unreachable!("typechecked")
                };
                let tmp = self.fresh();
                writeln!(
                    self.out,
                    "  %{} = load {}, ptr {}",
                    tmp,
                    llvm_ty(pointee.as_ref(), self.structs),
                    v
                )
                .unwrap();
                ((*pointee).clone(), format!("%{tmp}"))
            }
        }
    }
}

fn types_match(a: &Ty, b: &Ty) -> bool {
    match (a, b) {
        (Ty::I8, Ty::I8)
        | (Ty::U8, Ty::U8)
        | (Ty::I16, Ty::I16)
        | (Ty::U16, Ty::U16)
        | (Ty::I32, Ty::I32)
        | (Ty::I64, Ty::I64)
        | (Ty::U64, Ty::U64)
        | (Ty::I128, Ty::I128)
        | (Ty::Isize, Ty::Isize)
        | (Ty::Usize, Ty::Usize)
        | (Ty::U128, Ty::U128)
        | (Ty::Bool, Ty::Bool)
        | (Ty::Unit, Ty::Unit) => true,
        (Ty::Array(ax, an), Ty::Array(bx, bn)) => an == bn && types_match(ax, bx),
        (Ty::Struct(x), Ty::Struct(y)) => x == y,
        (Ty::Ptr(x), Ty::Ptr(y)) => types_match(x, y),
        _ => false,
    }
}

fn emit_fn(f: &FnDef, structs: &[StructDef], fn_sigs: &HashMap<String, FnSig>) -> String {
    Gen::new(structs, fn_sigs).emit_fn(f)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{Parser, tokenize};
    use crate::typecheck::{check_fn, collect_sigs};

    fn emit(src: &str) -> String {
        let (structs, fns) = Parser::new(tokenize(src)).parse_file().expect("parse");
        let (struct_map, fn_sigs) = collect_sigs(&structs, &fns).expect("sigs");
        for f in &fns {
            check_fn(f, &struct_map, &fn_sigs).expect("typecheck");
        }
        emit_module(&structs, &fns, &fn_sigs)
    }

    #[test]
    fn codegen_contains_if_branching() {
        let ll = emit(include_str!("../examples/tests/ok_if_return.nia"));
        assert!(ll.contains("br i1"));
        assert!(ll.contains("if.then."));
    }

    #[test]
    fn codegen_contains_tuple_struct_ops() {
        let ll = emit(include_str!("../examples/tests/ok_tuple_struct.nia"));
        assert!(ll.contains("insertvalue %struct.Foo"));
        assert!(ll.contains("extractvalue %struct.Foo"));
    }

    #[test]
    fn codegen_contains_print_for_primitives() {
        let ll = emit(include_str!("../examples/tests/ok_print_primitives.nia"));
        assert!(ll.contains("@printf"));
        assert!(ll.contains("nialang.std.fmt"));
    }

    #[test]
    fn codegen_pointer_load_present() {
        let ll = emit(include_str!("../examples/tests/ok_pointers.nia"));
        assert!(ll.contains("load i32, ptr"));
        assert!(ll.contains("define i32 @id_ptr"));
    }

    #[test]
    fn codegen_named_struct_type_decl_present() {
        let ll = emit(include_str!("../examples/tests/ok_struct_named.nia"));
        assert!(ll.contains("%struct.Bar = type"));
    }

    #[test]
    fn codegen_tuple_named_mix_contains_pair_and_boxed() {
        let ll = emit(include_str!("../examples/tests/ok_tuple_named_mix.nia"));
        assert!(ll.contains("%struct.Pair = type"));
        assert!(ll.contains("%struct.Boxed = type"));
        assert!(ll.contains("extractvalue %struct.Pair"));
    }

    #[test]
    fn codegen_nested_if_has_multiple_labels() {
        let ll = emit(include_str!("../examples/tests/ok_nested_if.nia"));
        let count_then = ll.matches("if.then.").count();
        assert!(count_then >= 2, "IR:\n{ll}");
    }

    #[test]
    fn codegen_contains_array_type_and_insertvalue() {
        let ll = emit(include_str!("../examples/tests/ok_array.nia"));
        assert!(ll.contains("[8 x i8]"), "IR:\n{ll}");
        assert!(ll.contains("insertvalue [8 x i8]"), "IR:\n{ll}");
    }

    #[test]
    fn codegen_contains_array_index_gep() {
        let ll = emit(include_str!("../examples/tests/ok_array_index.nia"));
        assert!(ll.contains("getelementptr inbounds [8 x i8]"), "IR:\n{ll}");
        assert!(ll.contains("load i8"), "IR:\n{ll}");
    }

    #[test]
    fn codegen_println_array_uses_array_text_constants() {
        let ll = emit(include_str!("../examples/tests/ok_print_array.nia"));
        assert!(ll.contains("nialang.std.txt.arr_open"), "IR:\n{ll}");
        assert!(ll.contains("nialang.std.txt.arr_sep"), "IR:\n{ll}");
        assert!(ll.contains("nialang.std.txt.arr_close_ln"), "IR:\n{ll}");
    }

    #[test]
    fn codegen_println_structs_and_ptr_hex() {
        let ll = emit(include_str!("../examples/tests/ok_print_structs.nia"));
        assert!(ll.contains("nialang.std.txt.obj_open"), "IR:\n{ll}");
        assert!(ll.contains("nialang.std.txt.tuple_open"), "IR:\n{ll}");
        assert!(ll.contains("nialang.std.fmt.ptrhex"), "IR:\n{ll}");
        assert!(ll.contains("ptrtoint ptr"), "IR:\n{ll}");
    }
}
